### ISSUE TITLE
formatting fastq data correctly

### ISSUE THREAD

**Issue by bioinfowheat** [bcgsc/arcs#100]
Hello,

I'm really keen on trying arcs, but am having a very difficult time getting my fastq data processed. I did just run it through longranger basic

longranger basic --id=ID --fastqs=files/ --sample=Polygonia --localcores=20 --localmem=100

# but when I compare the fastq headers, I have not achieved the BZ header with bar code. How do I do this?

# compare fastq headers 
# original 10x fastq
zcat /mnt/griffin/chrwhe/Polygonia_calbum/10x/longranger/files/Polygonia_S1_L001_R1_001.fastq.gz | \
sed -n '1~4p' | head
@ST-E00201:240:HCHJCCCXY:5:2224:21460:72280 1:N:0:CCACTACA
@ST-E00201:240:HCHJCCCXY:5:2224:21420:72280 1:N:0:TGCGGCTT
@ST-E00201:240:HCHJCCCXY:5:2224:21257:72280 1:N:0:ATGAAGAC
@ST-E00201:240:HCHJCCCXY:5:2224:21237:72280 1:N:0:CCACTACA
@ST-E00201:240:HCHJCCCXY:5:2224:21217:72280 1:N:0:ATGAAGAC
@ST-E00201:240:HCHJCCCXY:5:2224:20791:72280 1:N:0:GATTCTGG

# longranger processed
zcat /mnt/griffin/chrwhe/Polygonia_calbum/10x/longranger/ID/outs/barcoded.fastq.gz | \
sed -n '1~4p' | head
@ST-E00201:240:HCHJCCCXY:5:1201:21937:40407
@ST-E00201:240:HCHJCCCXY:5:1201:21937:40407
@ST-E00201:240:HCHJCCCXY:5:2122:12966:12173
@ST-E00201:240:HCHJCCCXY:5:2122:12966:12173
@ST-E00201:240:HCHJCCCXY:5:1109:17807:72420
@ST-E00201:240:HCHJCCCXY:5:1109:17807:72420

#long ranger fastq head
zcat /mnt/griffin/chrwhe/Polygonia_calbum/10x/longranger/ID/outs/barcoded.fastq.gz | head
@ST-E00201:240:HCHJCCCXY:5:1201:21937:40407
GAACATAATGTGCGTGAATCGAACAATAAAATGCTGGACGTGTTCACCGGTTCTAGTTTTTATATAGAATAACACTTTGTATCACTGCTTTTAAAAGTTTGAATGATCGTGGAATACATATTATGCTA
+
AFAF<JFFJ<F-<-7F<-<<7FJA<<JJJFJ7-77<7F7F77-<7A<7<7-77FJJJF<FJ-A--A7AJ-7F<FF-7J<<J<-FA--AJJ<7-AAAFAJ-77FJF<-7FFFAAA-77AF---77-7AA
@ST-E00201:240:HCHJCCCXY:5:1201:21937:40407
CTCTCCTCTACCAAAGGTTGCCTGGAAGAGATCGCTGTTTTAGCGATAAGGCCGCCTATTGTACATTTTTCTTTTCTTTGTTTTTGTTTTACTCCTATTATTTTTGTCTATATTGGTGTGCAATAAAGAGTATATAAATAAATAAATAAAA
+
AAAFFJJJJJJFJFFJFFJFFJJJA7A-FFFJJFJFFJAFJJJJAJJJJJJJJJJJJAJJJJJJJJJJJJJAJFJAAJJJFFJJFJJJJJJJAJFJJJFJJJJJJJFJFJJJJJJFJFJJJJAAFJFJJ-<<FFJF-7FJFFJFJFJJFAJ
@ST-E00201:240:HCHJCCCXY:5:2122:12966:12173
GCGAATTTATAATTTGTTTGACATATTAGTTTGCAACATCTATGAACGCGCTTAATAAAATTTATGCTTTCAAATCGTAATATATAATATATTATTAATATATATTGCATTTAGTTTTAACTATGTTG
+
JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFJJJJJJJJJJJJJFJJJJJJJJJJJJJJJJJJJJFJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJA-AFJJJJJJJJJFF<
@ST-E00201:240:HCHJCCCXY:5:2122:12966:12173
GGCTGTTTAAAAAAAAGGTTACTTATTTGGACATTAAATATAATGATTGGTGATTAGTCCGGCTTGGAATCCGGGACTTTGGGACAGCACTATTAGCACTAATTTAATATAACCACTAAGCCAACAACATAGTTAAAACTAAATGCAATAT
+
AAFFFJFJJJJJJJJJJJJJFJJJJJJJFJJJJJJJJJJJJJJJJJFJJJFFJJJJFJJJJFJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ

**Comment by lcoombe** [comment]
Hi @bioinfowheat,

Have you just looked at the `head` of your longranger processed file, or have you looked further down? (Ex. you could do a `gunzip -c my_reads.fq.gz |grep "BX"` or similar)

`longranger basic` will by default sort the output by barcode, thus reads that do not have an associated barcode appear first in the file. So I'd double check that the barcodes aren't really there, just not in the first few read pairs.

I hope that helps - thank you for your interest in ARCS!
Lauren

**Comment by bioinfowheat** [comment]
Thanks! I just in fact was looking deeper into my file and ....

zcat barcoded.fastq.gz | sed -n '1~4p' | grep 'BX' | wc -l
336,697,124 # ctq cleaned

so full steam ahead ... thanks and apologies for not digging deeper sooner.
cheers,
C

**Comment by lcoombe** [comment]
Excellent! I'm glad the data was fine after all :) Good luck with you ARCS runs!
