### ISSUE TITLE
scaffold headers are too long

### ISSUE THREAD

**Issue by grendon** [bcgsc/arcs#106]
Hi, thank you for making this tool available to all. It works fine.
However, tools like BUSCO have a hard time with the long scaffold headers. 
Is there a parameter that I can use to ask the tool to output short headers?

For example; this is how the headers of my scaffolded assembly file look like:

<pre>
>scaffold1,100488562,r118z992350k47a0m100_f660z527803k53a0m100_f14z873675k82a0m100_f180z1917129k65a0m100_r51z3829072k48a0m100_f31z1674794k51a0.09m100_r43z6054937k7a0.85m100_f261Z84618802
>scaffold2,91386886,f402z637824k23a0m100_f339z1767760k26a0m100_r126z2203978k21a0.23m100_f124Z83082742k82a0m100_f179z2165681k56a0.05m100_r385z853482k6a0m100_f511z675419
>scaffold3,79781986,f379Z79781986
>scaffold4,72786988,f164Z72786988
>scaffold5,79549855,f673z142769k5a0m100_f228z16143296k72a0.05m100_f187Z63263790
>scaffold6,69491944,f47z10726115k45a0m100_f318Z58658215k14a0.71m100_f737z107614
>scaffold7,49924990,f52z5356623k61a0m100_f291Z44568367
>scaffold8,102937753,r346z1693278k24a0.58m100_r168z12366653k78a0m100_f134Z43488697k106a0m100_f23z41437250k25a0.76m100_r165z922179k27a0m100_f107z1600726k38a0.26m100_f933z100013k37a0.16m100_r1069z56714k15a0m100_r2z330601k10a0.8m100_r684z215836k50a0m100_f445z385204k49a0.20m100_f862z97184k30a0.1m100_r688z100300k34a0.08m100_r330z143118
>scaffold9,38574249,f48Z37743062k30a0.4m100_r82z663429k49a0m100_r442z167758
>scaffold10,45880949,r235z10877141k61a0.16m100_f73Z35003808
>scaffold11,39671784,r843z68886k34a0m100_f366z916754k7a0m100_r133z246777k21a0.14m100_f208Z34107148k29a0.62m100_r355z1089746k61a0m100_r212z2247385k30a0.16m100_r219z995088
>scaffold12,36473483,f333z1600009k25a0.6m100_r444z672477k16a0m100_f72Z30138202k81a0m100_r131z4062795
>scaffold13,53481410,f306z921583k61a0.04m100_r643z859959k41a0.46m100_f4Z27303524k46a0.10m100_r42z23925542k63a0.12m100_r369z470802
>scaffold14,28524402,r652z258912k27a0.22m100_f216z606741k43a0m100_r455z629271k25a0.16m100_f840z108844k40a0.25m100_f748z65217k52a0.25m100_r320z827255k10a0.4m100_f70Z21238402k17a0m100_r327z266287k301a0.39m100_r123z4523473
>scaffold15,20465803,f6Z20204756k14a0.78m100_f156z261047
>scaffold16,17756631,f65Z17756631
>scaffold17,17610423,f97Z17610423
>scaffold18,21877070,f269z4457287k26a0m100_f83Z17419783
>scaffold19,23381655,r40z3252120k32a0.25m100_r741z128557k10a0m100_r153z711404k17a0.29m100_f196Z13466189k85a0.04m100_r24z5823385
>scaffold20,12673283,f87Z12541218k102a0.87m100_r389z132065

</pre>

**Comment by kmnip** [comment]
You can rename the fasta headers with integers using `awk`:
`awk '/^>/{$0=">"++i}1' scaffolds.fa > scaffolds_renamed.fa`

**Comment by grendon** [comment]
Will do. Thanks
