### ISSUE TITLE
Feature request: include a gfa file in output

### ISSUE THREAD

**Issue by ckeeling** [bcgsc/arcs#108]
Hello,

I'm looking at using the output assembly from arcs for input into SALSA2, which can optionally take a gfa file of the input assembly to improve its assembly. You already include the gv file in the output. Is it possible to create the gfa file too? Or, do you know of a method to create a gfa file from the gv and fasta files?

Cheers,
Chris

**Comment by ckeeling** [comment]
Thanks Lauren, I'll take a look.

**Comment by lcoombe** [comment]
Hi @ckeeling  - Sorry, I missed this somehow!

To be clear, do you want to use the ARCS graph, or the graph post-LINKS? `abyss` should be compatible with the `dist.gv` ARCS output.

**Comment by ckeeling** [comment]
Sorry @lcoombe I moved on to a different way of doing things and may not benefit from this anymore. However, what I was looking for was a gfa representation of the final output of arcs+LINKS for including as input to [SALSA2](https://github.com/marbl/SALSA), which optionally takes the input assemblies gfa to guide its scaffolding process. I wasn't using arcs+LINKS as part of the full ABySS pipeline.

I also misread your earlier comment on using the dist.gv; I used a different .gv above.

However, I get a different error when I use the dist.gv:

```bash
abyss-todot --gfa2 assembly_c5_m50-10000_s98_r0.05_e30000_z1000.dist.gv
H	VN:Z:2.0
S	6997	203040	*
S	6994	237268	*
S	6993	5212053	*
S	6991	6769632	*
S	6990	191410	*
S	6986	138532	*
S	6980	13030	*
S	6978	13497	*
...
S	5081	789	*
S	5082	1941	*
S	5084	1965	*
S	5085	14207	*
abyss-todot: GfaIO.h:83: std::ostream& write_gfa2_edge(std::ostream&, const Graph&, typename boost::graph_traits<Graph>::edge_iterator) [with Graph = ContigGraph<DirectedGraph<ContigProperties, Distance> >; std::ostream = std::basic_ostream<char>; typename boost::graph_traits<Graph>::edge_iterator = DirectedGraph<ContigProperties, Distance>::edge_iterator]: Assertion `distance <= 0' failed.
Aborted
```

**Comment by lcoombe** [comment]
Hi @ckeeling,

Oh yes, there are often just bits and pieces within ABySS that are useful by themselves - not just in the context of the full ABySS pipeline.

I'd have to look into why the `--gfa2` is giving that error - can you use GFA1? The command works fine for me with that option.

Keep me updated with whether this feature would still be helpful for you - we are quite busy right now, but I can keep it on my radar.
