### ISSUE TITLE
Regarding the error info "File contains unpaired reads"

### ISSUE THREAD

**Issue by Veldem** [bcgsc/arcs#110]
Dear All,

I try to scaffold the contigs of fish species using pair-end stLFR linked reads, here is my code:

arcs --arks -f genome.nextpolish.fa -a fastq_files.txt -t 40

fastq files:
Clean_Fish-TissueA_converted_R1.fastq.gz
Clean_Fish-TissueA_converted_R2.fastq.gz

first 4 lines of pair-end files:

Forward
@CL100158617L1C001R001_0#43_309_181/1 BX:Z:43_309_181
AATCTTTGTTAACCACTAACATTTCCAATCAAGCAACATGATATCCACTAAAACACATGCAGTATCCACAGTATGCATCTATAAAACAGGAAATCTTTTT
+
DACDDDEDCDCCEDAEEBBEDDCDED@DDDC@DDCDDDEDAECDDDDCECCDDDCE?ECEDEDCDDDDDBBEDDDDBDEDDDBDBECBCDCDDDA4DD4C

Reverse
@CL100158617L1C001R001_0#43_309_181/2 BX:Z:43_309_181
TGGTTGTTGTACAAGAACAGACAAAAAGATTTCCTGTTTTATAGATGCATACTGTGGATACTGCATGTGTTTTAGTGGATATCATGTTGCTTGATTGGAA
+
DDCEEDEEDDCDCBDCCECECD@DDDCDCDEDEDDEEDDECDBDCEECBEBEDEEDCCE@EDDECDEDEDEEDBE4CDE4CEEBDEEDDBDDCDDEDDEB

My question is that I have received plenty of error info called "File contains unpaired reads" (nearly 700 million lines), the problem stems from my fastq headers?

Best wishes

**Comment by lcoombe** [comment]
Hello @Veldem,

It looks like you are supplying two separate fastq files (R1, R2) to ARCS? ARCS expects the input reads to be interleaved in a single file, versus having separate files for R1 and R2.

The easiest way to interleave these paired-end files is using `seqtk mergepe`. 

Hope that helps - thank you for your interest in ARCS!
Lauren

**Comment by Veldem** [comment]
Dear Icoombe,

As you said, I merged the two ".fastq" files using seqtk mergepe and then run the script. After processing data, three files indicated below obtained;

genome.nextpolish.fa.scaff_arks_c5_k30_j0.55_l0_d0_e30000_r0.05.dist.gv
genome.nextpolish.fa.scaff_arks_c5_k30_j0.55_l0_d0_e30000_r0.05_main.tsv
genome.nextpolish.fa.scaff_arks_c5_k30_j0.55_l0_d0_e30000_r0.05_original.gv

At that point, how can I obtain my scaffold fasta?  Is there any script for such a purpose?

Best wishes

**Comment by lcoombe** [comment]
Hi @Veldem,

We suggest using our provided Makefile for running the `arks` pipeline, which will do all the necessary steps for you.
Take a look at our README for more details: https://github.com/bcgsc/arcs#running-arcs-in---arks-mode

Let me know if you have any questions about using the `arcs-make` Makefile!

**Comment by Veldem** [comment]
Dear Icoombe,

As you indicated, I run the following script;

`/okyanus/users/veldem/01.Direct_Projects/06.Anchovy_Genome_Projects/04.Genome_Scaffolding/03.arks_scaffolding/arks/Examples/arks-make arks draft=genome.nextpolish.fa reads=sqkit_merged_stLFR_reads.fq.gz threads=48`

I am getting an error "make: *** No rule to make target `genome.nextpolish.fa.fa', needed by `genome.nextpolish.fa.renamed.fa'.  Stop." 

Apparently, I am doing something wrong, but I could not solve it yet. Thank you,

Best wishes

**Comment by lcoombe** [comment]
Hi @Veldem,

Notice for the example in that section: 
For example, to scaffold the assembly `my_scaffolds.fa` with the interleaved, longranger processed reads `my_reads.fq.gz`, specifying a kmer size of 60:
```
arcs-make arks draft=my_scaffolds reads=my_reads k=60
```
So, accordingly, try 
```
arcs-make arks draft=genome.nextpolish reads=sqkit_merged_stLFR_reads t=48
```

**Comment by Veldem** [comment]
Thanks, @lcoombe,

It works now seamlessly,

Best wishes

**Comment by lcoombe** [comment]
Excellent! Glad it's working for you :)
