### ISSUE TITLE
About Running ARCS in default mode

### ISSUE THREAD

**Issue by ClarenceHsiang** [bcgsc/arcs#114]
Dear ARCS team:
I ran the ARCS in default mode with the raw scaffold.fa and 10X linked reads by following command:

/data/share/tools/arcs/Examples/arcs-make arcs draft=10X-NANKO-linked_consensusScaffold reads=NK210Xreads z=1000

After the program finished the bam file, and an ERROR showed as below:

[bam_sort_core] merging from 192 files and 8 in-memory blocks...
echo 10X-NANKO-linked_consensusScaffold.sorted.bam > 10X-NANKO-linked_consensusScaffold_bamfiles.fof
arcs -f 10X-NANKO-linked_consensusScaffold.renamed.fa -a 10X-NANKO-linked_consensusScaffold_bamfiles.fof -v -c 5 -m 50-10000 -s 98 -r 0.05 -e 30000 -z 1000 -d 0 --gap 100 -b 10X-NANKO-linked_consensusScaffold_c5_m50-10000_s98_r0.05_e30000_z1000 --barcode-counts barcodeMultiplicityArcs.tsv
bash: arcs: command not found
make: *** [10X-NANKO-linked_consensusScaffold_c5_m50-10000_s98_r0.05_e30000_z1000_original.gv] Error 127

Is it the problem with arcs installation?

Thank you very much

**Comment by lcoombe** [comment]
Hi @ClarenceHsiang,

A couple of questions - how did you install ARCS? Can you double check that the `arcs` executable is on your `PATH`? Based on that error it looks like `arcs-make` isn't able to find the `arcs` binary in your `PATH`.

Hope that helps - thank you for your interest in ARCS!
Lauren

**Comment by ClarenceHsiang** [comment]
Thank you so much.
I solve the problem by adding the PATH.
Thanks to your kindness  :D

**Comment by lcoombe** [comment]
Excellent - I'm glad to hear that fixed the issue for you! :)
