### ISSUE TITLE
Short read length question:  can the tool accept 250?

### ISSUE THREAD

**Issue by grendon** [bcgsc/arcs#119]
Hi,
We are a sequencing facility and we have produced TellSeq reads of  length 150 on  NovaSeq instruments.
We are wondering if your tool will be able to work with short reads of length 250, that could be sequenced by a MiSeq instrument.

Are there any advantages or disadvantages that you know of?

Thanks.

**Comment by lcoombe** [comment]
Hi @grendon,

Though we haven't tried ARCS with reads longer than 150bp ourselves (most of the tests have been on 10x Chromium and stLFR linked reads, which usually have around that read length), I don't see any reason why 2x250bp reads wouldn't work just as well, if not perhaps a bit better. 
The reads are used for mappings to the input draft contigs to determine barcode 'hits' to the contig ends. For the default ARCS mode (using `bwa mem`) for read alignments, I think that if anything having longer reads could help achieve better mappings of reads near/partially in repetitive regions. For the ARKS mode (using exact kmer matching), I again don't think that the read length would have a big impact, but I don't think that longer would be detrimental

The only disadvantage that I can think of would be that I would expect that longer reads could take longer to map in either mode, so will probably have a longer run-time. But I don't think it would be unreasonably so.

Hope that helps - thank you for your interest in ARCS!
Lauren
