### ISSUE TITLE
Add optional dependency of pigz

### ISSUE THREAD

**Issue by aakashsur** [bcgsc/arcs#146]
Just noticed in the `arcs-make` file there this this line - 

```
# Use pigz or bgzip for parallel compression if available.
ifneq ($(shell command -v pigz),)
gzip=pigz -p$t
else
ifneq ($(shell command -v bgzip),)
gzip=bgzip -@$t
else
gzip=gzip
endif
```

It could be worth mentioning in the README file that there is an optional dependency to speed up compression with pigz.

**Comment by lcoombe** [comment]
Hi @aakashsur,

Thanks for the comment - but actually we don't use any of those compression tools in the default ARCS/ARCS-long/ARKS/ARKS-long pipelines right now. Those lines are left for developer convenience, but your run won't be impacted by whether you have `pigz` available or not.

Thanks!
Lauren
