### ISSUE TITLE
empty graph.gv file

### ISSUE THREAD

**Issue by Hazelhuangup** [bcgsc/arcs#15]
I am currently dealing with the scaffolding of a plant genome with ARCS, but got blocked because there is no content in the output graph.gv file from ARCS (graph{}).

I've attached the Barcode index to the reads name and sorted the alignment file( bwa0.7.15) in order if reads name. I’ve tries both 15 and 85 fold of 10X reads, but neither of them works. There is no error reported and the log file ended with “Done!"

The reference data set was resulted from Supernova assembly, it is noteworthy that only those scaffolds from one specific chromosome were used as input(we have done genetic mapping). I wonder if this gonna trigger the error?

The test dataset of human genome worked quite well so I bet there is no problem with the installation.

Here is my command line for running ARCS:
arcs -f ./10X_asm_megabubbles_2_2.fasta -a bam.list -s 98 -c 5 -l 0 -z 1000 -m 5-10000 -d 0 -e 30000 -r 0.1 -v 1

I've tried -s 90, it didn't work either.

**Comment by conniecl** [comment]
https://github.com/bcgsc/arcs/issues/9, have a look to seem if it solved your problem?

**Comment by lcoombe** [comment]
@Hazelhuangup - I'm closing this old issue -- feel free to re-open or start another issue!
