### ISSUE TITLE
`arcs-tigmint` and `arks-tigmint` struggle with input files outside working directory

### ISSUE THREAD

**Issue by taprs** [bcgsc/arcs#159]
Dear BCGSC team, thank you for this brilliant tool!

I experienced an overcomable yet unexpected error when running `arcs-make arcs-tigmint` or `arcs-make arks-tigmint` giving full paths (containing slashes) for the `draft` and `reads` parameters. This caused an error with `bwa mem` temporary directory creation. Here is the relevant part of the logfile:

```
. . .
[main] CMD: bwa index /path1/contigs.fa
[main] Real time: 495.637 sec; CPU: 489.737 sec
bwa mem -t40 -pC /path1/contigs.fa /path2/reads.fq.gz | samtools view -u -F4 | samtools sort -@40 -tBX -T$(mktemp -u -t /path1/contigs./path2/reads.sortbx.bam.XXXXXX) -o /path1/contigs./path2/reads.sortbx.bam
mktemp: invalid template, '/path1/contigs./path2/reads.sortbx.bam.XXXXXX', contains directory separator
[E::hts_open_format] Failed to open file "/path1/contigs./path2/reads.sortbx.bam" : No such file or directory
samtools sort: can't open "/path1/contigs./path2/reads.sortbx.bam": No such file or directory
. . .
[M::mem_pestat] skip orientation RR
[M::mem_process_seqs] Processed 4000000 reads in 5267.345 CPU sec, 133.620 real sec
time user=5214.87s system=65.71s elapsed=147.13s cpu=3589% memory=23961 job=
time user=0.01s system=0.01s elapsed=144.50s cpu=0% memory=6 job=
time user=0.01s system=0.01s elapsed=0.06s cpu=24% memory=6 job=
tigmint-make:162: recipe for target '/path1/contigs./path2/reads.sortbx.bam' failed
make[1]: *** [/path1/contigs./path2/reads.sortbx.bam] Error 1
make[1]: Leaving directory '/pwd'
make: *** [/pwd/contigs.tigmint.fa] Error 2
```

I did not get this error with `arcs-make arcs`, though. 

Right now I use a workaround of making symlinks for `/path1/contigs.fa` and `/path2/reads.fq.gz` in `/pwd`. Is it possible to account for probability of having full paths to input files?

**Comment by lcoombe** [comment]
Hi @taprs,

Thank you for your kind words!

Yes, currently as you pointed out, we require the input files to be in the current working directory, and we suggest using symlinks to achieve this.
We don't seem to have a note about that in this README - I can update that and thank you for pointing it out! 
The limitation currently is that Tigmint uses the input read/assembly names for the output file names. Thus, when you provide full names, that is the issue. We can certainly take a look at changing that scheme in the future. In the meantime, I'll add better documentation to help out future users.

Thank you for your interest in ARCS and Tigmint!
Lauren
