### ISSUE TITLE
Link to paper and LINKS software in README.md ?

### ISSUE THREAD

**Issue by jvhaarst** [bcgsc/arcs#17]
Hi,

Right now, there is no link to the paper or the LINKS software, which makes it a bit harder to use your software.

Dag,
Jan

For other people :
Paper : 
             https://doi.org/10.1101/100750
LINKS :  
             http://www.bcgsc.ca/platform/bioinfo/software/links
             https://github.com/warrenlr/LINKS

**Comment by warrenlr** [comment]
thanks your your comment. I added those links to the README.
Rene
