### ISSUE TITLE
Mean gaps in .scaffolds csv file are all the same

### ISSUE THREAD

**Issue by Hazelhuangup** [bcgsc/arcs#19]
In your demo and my own genome, all the mean gaps are estimated to 10, Here is an example:
scaffold77,942471,f15191z72983k40a0.07m10_f13167z221844k4a0.5m10_f15280Z481647k5a0.6m10_f530z165997
scaffold78,1050735,r8877z5568k5a0.6m10_r984z132808k2a0.5m10_f127z174327k6a0.5m10_f128Z473863k23a0.17m10_f129z264169
scaffold79,571225,r15084z29962k16a0.12m10_f165z72736k2a0.5m10_f785Z468527
Does this mean LINKS don't do the estimation? and under what circumstances will this function work?

**Comment by warrenlr** [comment]
10bp was chosen arbitrarily, and set within the ARCS code. When used in conjunction with the LINKS scaffolder, LINKS only uses the information passed on by ARCS (including the gap size set at 10bp)
At this point, we are not estimating the gap/overlap length in ARCS - this feature will come later

**Comment by Hazelhuangup** [comment]
Thanks for your response.

**Comment by melop** [comment]
Hello, is there any updates on adding gap size estimation? This functionality would be very useful.

**Comment by warrenlr** [comment]
Yes, indeed, it would be very useful !

We are working on it, but I am afraid I don't have an ETA for you

**Comment by melop** [comment]
So what I notice is that after scaffolding with ARCS and linkage map assignment, some of the chromosomal regions appear to be contracted (you can see on Loupe viewer that the shared reads drop below the neighboring regions). I think that would provide a signal for correcting for the gap size.
Hopefully you guys can work out a solution soon.

Best,
Ray

**Comment by warrenlr** [comment]
yes, the contraction is expected since the gap size is arbitrarily set at 10bp (which was chosen for practical reason, not at all based on estimates).  this is valuable insights Ray, thank you for sharing.  cheers, rene

**Comment by ValentinaPeona** [comment]
Hi,
is there a way to set manually the length of the inserted gaps with ARCS? Can I just put the gap length I'd like in the last column of the tsv file?
I think it would be a useful option to include (thinking about hybrid assemblies and error correction with long reads).

Thank you,
Valentina

**Comment by warrenlr** [comment]
thank you for your comment, Valentina.  
Yes, you may put any gap length you'd like in the tsv file. 
We are working on gap length estimates and, when ready, the ARCS release will no longer be listing arbitrary gap lengths in the tsv file. 
Cheers, 
Rene

**Comment by melop** [comment]
Dear Rene,

       after playing with it for a while, I figured out a way to get a rough estimate of gap size. Not sure if you guys are along the same lines but I guess it would be good to share it.

       Basically I first used the long scaffolds as a reference, and calculate the proportion of shared barcodes between two windows of known distance in bp. Then I saw did log transformation on distance and shared barcode %, and found that they are largely linear.

       I then wrote an Rscript to predict the gap size based on shared barcodes between two windows.

Ray
[Rplots.pdf](https://github.com/bcgsc/arcs/files/1496636/Rplots.pdf)

**Comment by warrenlr** [comment]
Thanks for your message, Ray and for sharing your insights on gap size estimates. We appreciate the interest and participation from our users and the community. 
We have implemented a very similar approach, which it turns out, is also similar to how supernova generates its estimates. Recently, we have done a release for a [read] alignment-free version of the code. It's currently under review, so can't say too much at the moment.
Best regards,
Rene

(I don't understand the Rplots.pdf.. is the solid line the ground truth and dots estimates? if so, your predictor seems very robust)

**Comment by benvvalk** [comment]
@Hazelhuangup @melop @ValentinaPeona @warrenlr:

The latest ARCS release (https://github.com/bcgsc/arcs/releases/tag/v1.0.1) contains a first implementation of gap size estimation.  To enable it, add the `--dist_est` option.

Currently, the  error of the estimated distances is on the order of kilobases, so there is lots of room for improvement. 

Only gaps flanked by contigs lengths > 2 * `--end_length` will get distance estimates, so depending on the contiguity of the input assembly, it may be desirable to decrease `--end_length` from the default value of 30,000 bp.
