### ISSUE TITLE
Mapping of Chromium reads

### ISSUE THREAD

**Issue by danshu** [bcgsc/arcs#2]
Hi,

I'm interested in using arcs to scaffold my genome assembly using 10X genomics data. For the first mapping step, bwa mem with default parameters was used in the ABySS 2.0 preprint (http://biorxiv.org/content/early/2016/08/07/068338). 
My question is that, is "bwa mem with default parameters" enough for mapping Chromium data? Or other specialized linked-read alignment tool such as Lariat will improve final scaffolding results?

Best,
Quan

**Comment by danshu** [comment]
I have a few questions after reading the help information.
For the requirement of BAM alignment files, 
"     NOTE: alignments must be sorted in order of name
             index must be included in read name in the format read1_indexA
             read name must include a number"
Do you mean sort the alignment in order of read name or reference name?
Index is the the 10X barcode string of the form 'ACGTACGTACGTAC-1'?
What does "read name must include a number" mean?

**Comment by warrenlr** [comment]
please follow the instructions at:
ftp://ftp.bcgsc.ca/supplementary/ARCS/docs
and
ftp://ftp.bcgsc.ca/supplementary/ARCS/docs/arcsDemoScripts/readme.md

**Comment by danshu** [comment]
Thanks for your help!
