### ISSUE TITLE
How may mis-scaffolding happen

### ISSUE THREAD

**Issue by qihualiang** [bcgsc/arcs#21]
Hi ARCS developers,

I have a draft assembly based  on PacBio data and I used ARCS+LINKS pipeline to scaffold it with 10x data. I tuned ARCS parameter -r and -e and aligned scaffolds of different parameter sets to the optical map. The alignments to the optical map seem to show some mis-scaffolding. I read the pre-print paper and there is not much discussion on the mis-scaffolding. How may it happen? 
Besides of tuning -r and -e, what other parameters may also be helpful to improve scaffolding based on my data?

Thanks a lot
Qihua

**Comment by qihualiang** [comment]
Hi Rene,

Thanks for the suggestions on tuning LINKS parameters. I will try and see the alignments of new scaffolds with other available data.

Besides, recently I realize more than 1 (typically 1 to 10 according to 10x) HMW DNAs can be attached to the same GEM cell. Unlike 10x LongRanger which relies on a high quality reference and thus can cluster 10x reads based on the alignment locations, BWA alignments of 10x reads towards the draft assembly may not help to demultiplex 10x reads by the alignment locations along the reference.  I am interested in how ARCS deals with demultiplexing reads with the same barcode back to the same HMW DNA.

The pre-print ARCS paper does not explain this in details, is there other available materials explaining how ARCS is designed?

Thanks
Qihua

**Comment by warrenlr** [comment]
Hi Qihua,
Yes, that is correct - barcodes are reused.  
ARCS uses the number of barcodes supporting two sequences to suggest joins for LINKS.  We consider every possible pair of sequences and look at evidence (reads aligning to the sequence edges only) supporting a relationship between two sequences. When barcodes are re-used, the sequences those reads aligned to must be supported by multiple (LINKS -l) barcodes to be linked. Barcode re-used would have for effect to create tips in the graph, but they would not be supported by a majority of distinct barcodes if the edge is valid.  
I hope it makes sense.
Rene

**Comment by qihualiang** [comment]
Hi Rene,

I read the LINKS paper and I am still not clear about the algorithm part on picking dominant pairing(s) from all possible parings by -a. How is "maximum link ratio between two best contig pairs" calculated? Are we choosing among contig pairs that are supported by same multiple (LINKS -l) links?

Thanks
Qihua

**Comment by warrenlr** [comment]
Hi Qihua,

Please refer to slides 4 and 8 of this RECOMB presentation:

https://warrenlr.github.io/papers/2017_arcs_recombseq.pdf

Cheers,
Rene

**Comment by lcoombe** [comment]
Closing this old issue -- feel free to re-open if you still have questions.
