### ISSUE TITLE
running ARCS multiple times using newly scaffolded assembly as a reference

### ISSUE THREAD

**Issue by mikoze** [bcgsc/arcs#22]
Hi,

We're trying to improve our extremely fragmented fish genome assembly (number of scaffolds = 175785, scaffold N50 = 8335) using ARCS and 10x data. 
We have tested different parameters of ARCS and found that the following adjustments seem to work better with our data: s 98 -c 3 -l 0 -m 25-20000 -d 0 -r 0.05 -e 4000 -z 400. With LINKS we have used quite relaxed parameters: -l 2 -t 2 -a 0.9 -x 1 -z 400.
We have observed a substantial improvement after first run of ARCS+LINKS, number of scaffolds have been reduced to 158971, and scaffold N50 increased to 12248. We repeated the pipeline 4 times, every time using newly scaffolded assembly as a reference.
Now after four rounds we've got 134882 scaffolds with scaffold N50 = 95581. BUSCO analysis is also showing an improvement, completeness has been increased from 53.1% to ca 70%.

The question is: is it sensible to run several rounds of ARCS+LINKS pipeline? 

P.S. We're also running Supernova, however, without any result for more than 3 weeks...

**Comment by warrenlr** [comment]
Thank you for sharing your results, we are grateful to receive this feedback and see how useful ARCS/LINKS has been in your project.

It is sensible to use it iteratively;

We have done limited iterative tests in the past, and our starting assembly was quite contiguous perhaps it is why we did not observe appreciable gains after the 2nd iteration. It makes sense that you would be making merges after several iterations, as the scaffold graph becomes simpler and simpler, with less conflicts. I recommend trying another set of iterative scaffolding, but with more stringent (-c 4/5, -l 5, -a 0.3/0.5/0.7) parameters this time and compare both resulting assemblies for completeness (with BUSCO).
Cheers,
Rene

**Comment by mikoze** [comment]
Thank you, Rene, for quick reply!
We will try running ARCS+LINKS with more stringent parameters.
Best regards,
Mikhail

**Comment by mikoze** [comment]
Hi Rene,

I have tried more stringent parameters and, unfortunately, after examining the scaffolds after ARCS-LINKS pipeline, I realized that the scaffolds that I've obtained were chimeric. I've plotted the start and end of each barcode (>10) in new scaffolds to visualize the pattern. 

The parameters that I've used for ARCS:
s 98 -c 5 -l 0 -m 25-20000 -d 0 -r 0.05 -e 30000 -z 400
for LINKS:
-l 5 -t 2 -a 0.7 -x 1 -z 400

Here are some examples:
![image](https://user-images.githubusercontent.com/33651367/33553607-1fb452ba-d902-11e7-8e5c-ddaa6c40842a.png)
![image](https://user-images.githubusercontent.com/33651367/33553622-2a8e902e-d902-11e7-8580-3869facf136c.png)
![image](https://user-images.githubusercontent.com/33651367/33553766-a90de8e6-d902-11e7-80e2-17a56e7224b3.png)

On the other hand, it seems that there is lot of information in the data. 
Is there a way to get our assembly more continuous, and keeping errors at low level? 
Playing with -e parameter? Something else?

best regards,
Mikhail

**Comment by warrenlr** [comment]
Thank you for the insights Mikhail.
The question is, were they misassembled to begin with?  We are actively developing a correction utility to help catch these and rectify assemblies (under review).  Because ARCS looks at -e bases for scaffolding, and the ends might be misassembled to begin with, I recommend augmenting -e (we have done limited tests with -e 60000). If you suspect that the misassemblies you are seeing are induced by ARCS, I recommend increasing -l (10, 15, 20..) and decreasing -a (0.1, 0.2, 0.3, ..).
Thank you for sharing,
Rene

**Comment by mikoze** [comment]
Thank you, 

I'll try more stringent parameters.
I suppose that misscafolding most likely was introduced after ARCS in our case. 
Here are the examples of barcode distribution in some original longest scaffolds from the CLC assembler:

![image](https://user-images.githubusercontent.com/33651367/33594833-3529389e-d99e-11e7-819b-086b6edeff74.png)
![image](https://user-images.githubusercontent.com/33651367/33594845-3fc16e20-d99e-11e7-8812-4732697bbde5.png)

Best regards,
Mikhail

**Comment by lcoombe** [comment]
Closing this old issue -- feel free to re-open if you still have questions.
