### ISSUE TITLE
empty XXXX_original.gv file

### ISSUE THREAD

**Issue by tiramisutes** [bcgsc/arcs#24]
Hello,
I'm pretreatment my 10x pair reads with [https://github.com/tiramisutes/proc10xG](https://github.com/tiramisutes/proc10xG) scripts and then run ARCS as follows:
```
arcs -f genome.fa -a BAM.list -s 98 -c 5 -m 50-1000 -d 0 -r 0.05 -e 30000 -b XXXX
```
The output is normal and not any error. But finally the XXXX_original.gv file is empty. What's happend? 
```
Running: arcs 1.0.1
 pid 83323
 -c 5
 -d 0
 -e 30000
 -l 0
 -m 50-1000
 -r 0.05
 -s 98
 -v 0
 -z 500
 --gap=100
 -b AS_2BESST
 -g NA
 --barcode-counts=NA
 --tsv=NA
 -a BAM.list
 -f genome.fa

=>Getting scaffold sizes... Tue Jan  2 10:59:29 2018

=>Starting to read BAM files... Tue Jan  2 10:59:36 2018
{ "All_barcodes_unfiltered":0, "All_barcodes_filtered":0, "Scaffold_end_barcodes":0, "Min_barcode_reads_threshold":50, "Max_barcode_reads_threshold":1000 }

=>Starting to write reads per barcode TSV file... Tue Jan  2 13:17:14 2018


=>Starting pairing of scaffolds... Tue Jan  2 13:17:14 2018

=>Starting to create graph... Tue Jan  2 13:17:14 2018

=>Starting to write graph file... Tue Jan  2 13:17:14 2018

      Max Degree (-d) set to: 0. Will not delete any vertices from graph.
      Writing graph file to XXXX_original.gv...

=>Starting to create ABySS graph... Tue Jan  2 13:17:14 2018

=>Starting to write ABySS graph file... Tue Jan  2 13:17:14 2018


=>Starting to write TSV file... Tue Jan  2 13:17:14 2018
```

**Comment by lcoombe** [comment]
Hello,
Would you be able to post a couple of lines of your draft assembly fasta file and your barcoded reads fastq? Often, an empty graph file is due to issues with formatting. Also, take a look at the documentation here: ftp://ftp.bcgsc.ca/supplementary/ARCS/docs/ - there are instructions for running ARCS there that may also help.
Lauren

**Comment by tiramisutes** [comment]
Thanks. I will check.

**Comment by lcoombe** [comment]
@tiramisutes - I'm assuming you were able to get ARCS running properly  -- feel free to re-open if you have further problems.
