### ISSUE TITLE
chimeric scaffolds detection with ARCS

### ISSUE THREAD

**Issue by dcopetti** [bcgsc/arcs#26]
hello,
I am wondering if I could use ARCS to detect misassemblies in my scaffold-level diploid assembly (produced from PE, MP and 10x data by NRGene), in particular with the caveat that I would be using the same 10x data that built the scaffolds.
If it won't work, do you have any idea of what I could use?
Thanks,
Dario

**Comment by benvvalk** [comment]
Hi @dcopetti,

Tigmint is probably the tool you are looking for: https://github.com/bcgsc/tigmint

@sjackman has some slides about the project here: https://github.com/sjackman/tigmint-slides

**Comment by sjackman** [comment]
Please use the `tigmint-span` branch rather than `1.0.0` or `master`. https://github.com/bcgsc/tigmint/tree/tigmint-span
We're actively working on its development. It should be merge into `master` and released in a couple of weeks.
