### ISSUE TITLE
End length is not 30k by default.

### ISSUE THREAD

**Issue by jvhaarst** [bcgsc/arcs#28]
In the code and manual it states that the end length that is being considered is 30k by default : 

https://github.com/bcgsc/arcs/blob/e75619fdadde4a6c0e1e97ebc20d58a15d7e45de/Arcs/Arcs.cpp#L45

But in the place where it is being set, it is set to zero : 
https://github.com/bcgsc/arcs/blob/ecd98d1c9dea316555065ef6962b18cd00729b8a/Arcs/Arcs.h#L65-L80

And where it is used, that zero is translated to "use half of the contig length" : 
https://github.com/bcgsc/arcs/blob/e75619fdadde4a6c0e1e97ebc20d58a15d7e45de/Arcs/Arcs.cpp#L306-L314

I don't know which is best, the default (0) might work fine for some projects, although I see that setting it to another number works better in the ones that I have tested so far.

But I think it is better to change either the default to 30K, or to change the manual and code to show the effect of using 0 as default.

**Comment by jvhaarst** [comment]
I have created a pull request to set the default to 30k : 
#29

**Comment by warrenlr** [comment]
Thank you for identifying this bug, @jvhaarst !
@benvvalk, could we also please apply this bug fix in ARKS
Thanks,
Rene

**Comment by benvvalk** [comment]
@warrenlr Yep, I fixed it in ARKS as well.  (Thanks for the reminder.)
