### ISSUE TITLE
Error in sorting order of BAM files

### ISSUE THREAD

**Issue by danshu** [bcgsc/arcs#3]
Hi,

I have the following problem in running Arcs:
```
ERROR! BAM file should be sorted in order of read name. Exiting... 
 Prev Read: ST-E00129:523:HC2HTALXX:3:1101:1083:65283_ATGGCCGTCACAGCCG; Curr Read: ST-E00129:523:HC2HTALXX:3:1101:1083:65318_AACCCTCCATGACGGA
```

I mapped and sorted the bam file following the instructions. I removed duplicate reads using MarkDuplicates and then I have this error in runing Arcs. I sorted my Bam file again using "samtools sort -n" or "picard.jar SortSam  SORT_ORDER=queryname" but didn't solve the problem.

Best,
Danshu

**Comment by warrenlr** [comment]
Hi Danshu, I have not experienced this bug yet.  The first thing I can think of that may throw this error is a missing read. Ensure that your starting file (bam, 2 fastq's or interleaved fastq has both reads of a pair). Also, the instructions given for alignment expected interleaved fastq, supplied in bwa mem via the -q option. If you have another read format, please change the command accordingly.

**Comment by sjackman** [comment]
If you have a mixture of paired and unpaired reads in you BAM file, see PR https://github.com/bcgsc/arcs/pull/1, which was just merged, that skips unpaired alignments.

**Comment by sjackman** [comment]
You may wish to try building the Git `master` branch using Linuxbrew
See http://linuxbrew.sh
then `brew install --HEAD homebrew/science/arcs`

**Comment by danshu** [comment]
Thanks! Using the "develop" branch, I can finish running Arcs.
