### ISSUE TITLE
Length of fasta sequences vs @SQ and masking

### ISSUE THREAD

**Issue by mp15** [bcgsc/arcs#32]
I am attempting to scaffold some output from HGAP which marks sequence as upcase or lowercase by default as part of output. I mapped my input sequences using BWA MEM but ran into the error ```error: mismatched sequence lengths: sequence 004574F|arrow: 0 != 4531``` and realised your definition of sequence length is different to BWAs because you exclude softmasked repeats from your length and this causes issues. Mainly because you exclude masked lowercase sequence, and BWA does not but you then check ```@SQ``` lengths against the FASTA length by your definition. What is the correct solution to this? It might be helpful to document for other lost travellers such as myself.

**Comment by sjackman** [comment]
Thanks for the bug report, Martin. I'll tag and release ARCS version 1.0.4 including this fix.

@lcoombe Are there any other changes to ARCS that ought to be included in the release?

**Comment by lcoombe** [comment]
Thanks @sjackman! I can't think of any other changes for the new release

**Comment by sjackman** [comment]
I've released version 1.0.4 of ARCS. https://github.com/bcgsc/arcs/releases/tag/v1.0.4

**Comment by shtist** [comment]
Hi. I am using the arcs version 1.0.4 but got error messages "error: mismatched sequence lengths:".
I have used the commands as follows

samtools faidx draft.fa
bwa index draft.fa
bwa mem -t80 -p -C draft.fa reads.fq.gz | samtools sort -@20 -tBX -T /tmp_brew -o draft.reads.sortbx.bam
tigmint-molecule draft.reads.sortbx.bam | sort -k1,1 -k2,2n -k3,3n >draft.reads.molecule.bed    
tigmint-cut -p20 -o draft.tigmint.fa draft.fa draft.reads.molecule.bed    
arcs-make arcs draft=draft.tigmint reads=reads ---> mismatched seq length error

**Comment by lcoombe** [comment]
Hi @shtist - Could you post the full ARCS log output? When you look at the sequence indicated as having mismatched sequence lengths in the BAM header vs in the fasta file, is the discrepancy due to lowercase sequence characters?
