### ISSUE TITLE
error in bam file?

### ISSUE THREAD

**Issue by jdmontenegro** [bcgsc/arcs#33]
Hi guys,
I recently mapped the demultiplexed reads from 10X chromium to a reference genome using bowtie2. As recommended the barcodes were attached to the read name as READNAME_BARCODE.
After the mapping finished I converted the sam file into a bam file using samtools and then used the bam for finding the links between contigs in a raw assembly. However I keep getting the following error:
```
On line 940000000
On line 950000000
On line 960000000
On line 970000000
On line 980000000
On line 990000000
On line 1000000000
On line 1010000000
On line 1020000000
On line 1030000000
On line 1040000000
error: `/data/Bioinfo/bioinfo-proj-jmontenegro/DENOVO/Dunnart/Results/Mappings/Bowtie/Abyss/10X_abyss.sam': Expected end-of-file and saw `2    127M    =       2707    -246    AGAAAATCTATGTGTGGGAATCTTCAGATAATCGTATGATTGAGCTTTACTAGCAACCATGGTATGGAGGTCATGGATTTACCCATTTCCCAAAGGAGAAATTCAGTGTTTATTGCCTTCTTAGAAT       IHFFCIHHHDHHCHIIIIHGIIIIIIGIHIHIIIIIIHIIIIIIIIHHFHHIIIIHIHHFIIIIIIIIIIIHGHGIIIIIHGIHIIIIHHHIHHIIIIIIIHHHIGIIIIIIIIIHIIIIIHIIIII        AS:i:-5 XN:i:0  XM:i:1  XO:i:0XG:i:0   NM:i:1  MD:Z:58T68      YS:i:-21        YT:Z:CP'
```
However I cannot see any issues in the bam file at all. At least while converting to bam, samtools did not detect any issues. Have you seen this error before?

Cheers,

**Comment by jdmontenegro** [comment]
BTW, I have also tried using the original sam file , but I get the same error.

**Comment by jdmontenegro** [comment]
Just sorted this out, it seems it was a memory issue where some sub-processess were being killed by the scheduler (slurm). Increasing requested memory fixed the issue and produced the _original.gv and the .gv files.

**Comment by lcoombe** [comment]
Glad you worked it out @jdmontenegro!
