### ISSUE TITLE
error: `@HD	VN:1.5	SO:unknown': No such file or directory

### ISSUE THREAD

**Issue by shtist** [bcgsc/arcs#35]
Hello!
I am trying to use arcs for scaffolding Pacbio draft genome sequences (draft.fa) by using 10X Genomics reads (reads.fq.gz).
By far I have used tigmint protocol with default options and it was OK. 
<commands that I have used for tigmint process>
samtools faidx draft.fa
bwa index draft.fa
bwa mem -t20 -p -C draft.fa reads.fq.gz | samtools sort -@20 -tBX -T /tmp_brew -o draft.reads.sortbx.bam
tigmint-molecule draft.reads.sortbx.bam | sort -k1,1 -k2,2n -k3,3n >draft.reads.molecule.bed    
tigmint-cut -p20 -o draft.tigmint.fa draft.fa draft.reads.molecule.bed 

However, at arcs steps I got these error messages "error: `@HD	VN:1.5	SO:unknown': No such file or directory"
> arcs -f draft.tigmint.fa -a draft.reads.sortbx.bam
Running: arcs 1.0.3
 pid 13640
 -c 5
 -d 0
 -e 30000
 -l 0
 -m 50-10000
 -r 0.05
 -s 98
 -v 0
 -z 500
 --gap=100
 -b draft.tigmint.fa.scaff_s98_c5_l0_d0_e30000_r0.05
 -g draft.tigmint.fa.scaff_s98_c5_l0_d0_e30000_r0.05.dist.gv
 --barcode-counts=NA
 --tsv=NA
 -a draft.reads.sortbx.bam
 -f draft.tigmint.fa
=> Getting scaffold sizes... Mon Jul  2 14:37:54 2018
=> Reading alignment files... Mon Jul  2 14:38:02 2018
error: `@HD	VN:1.5	SO:unknown': No such file or directory

Could you help or recommend me how to handle these errors?

**Comment by lcoombe** [comment]
Hello @shtist,

It looks like you are providing the direct BAM file in the ```-a``` option, instead of a text file listing the input SAM/BAM filenames. Try making a text file with ```draft.reads.sortbx.bam``` in it, then specifying this file for the ```-a``` option.

Hope that helps!
Lauren

**Comment by lcoombe** [comment]
I'm closing this issue for now -- feel free to re-open if you have additional questions!
