### ISSUE TITLE
small correction for parallelisation of bwa in arcs-make

### ISSUE THREAD

**Issue by rahulvrane** [bcgsc/arcs#37]
Hi Thanks a lot for this package! I found a small change for running BWA in parallel that might help:
arks-make command on line 138 is:
`	/usr/bin/time -v sh -c 'bwa mem -t$t -C -p $< $(reads).fq.gz | samtools view -Sb - | samtools sort -@$t -n - -o $@' |& tee $(patsubst %.sorted.bam,%,$@)_bwa_mem.log
`    
should be:
`	/usr/bin/time -v sh -c 'bwa mem -t$(threads) -C -p $< $(reads).fq.gz | samtools view -Sb - | samtools sort -@$t -n - -o $@' |& tee $(patsubst %.sorted.bam,%,$@)_bwa_mem.log
`

**Comment by lcoombe** [comment]
Thanks for the report @rahulvrane! 

I fixed this issue in 011de72 -- The usage page now correctly shows that ```t``` (not ```threads```) specifies the number of threads to use for the BWA alignment (and tigmint, if it is run before ARCS)
