### ISSUE TITLE
BAM FILES input

### ISSUE THREAD

**Issue by Grelot** [bcgsc/arcs#40]
Hi,
It's more a question about how to use arcs than to report an issue.

I see arcs need bam files and fasta file as input. I understand the fasta file is the scaffolds sequences but i don't really understand what are the bam files ?

Are they chromium "linked-reads" output ? From which softwares ? supernova produces fasta files, otherwise, i see that cellranger produces bam files.
Can you explain me how i can generate bam files from chromium data ?

cheers

**Comment by lcoombe** [comment]
Hello @Grelot 

The BAM files are alignments of the linked reads to the draft scaffolds. We use ```bwa mem``` to generate these files.
Take a look at our Makefile (Examples/arcs-make), which you can directly use to run the entire ARCS pipeline, or at least will give you some guidance about the steps (and parameters/options) required in the pipeline.

Hope that helps!
Lauren

**Comment by lcoombe** [comment]
@Grelot - I'll close this, but feel free to re-open/open another issue if you have any further questions!
