### ISSUE TITLE
I get nothing in original.gv file

### ISSUE THREAD

**Issue by JhinAir** [bcgsc/arcs#42]
Hi,

I'm trying to use arcs pipeline and everything seems to run without error. But I got empty original.gv file.  I followed a pipeline aim to Acropora millepora Genome Assembly (Zachary L. Fuller, Yi Liao, Line Bay, Mikhail Matz & Molly Przeworski. August 2, 2018)

(1) 
Firstly, I used longranger-basic to deal with 10X data reads:
     ./longranger basic --id=Ass --fastqs=./10XData/ --sample=10X
It got me output: Ass/outs/barcoded.fastq.gz.

Then convert the fastq file:
      gunzip -c Ass/outs/barcoded.fastq.gz | perl -ne 'chomp;$ct++;$ct=1 if($ct>4);if($ct==1) if(/(@\S+)\sBX:Z:(\S{16})/){$flag=1;$head=$1."".$2;print "$head\n";}else{$flag=0;}}else{print "$_\n" if($flag);}' > CHROMIUM_interleaved.fastq.

     The output fastq is just like this:
     ###############################################
     (The first read_1_1)
     @CL100089928L2C009R030_475184AAACACCAGACAATAC
     AAAGTGATTGCGGTGCTGATTGTTGTAGTCTGTTGTTTACGGTATTCCC........
     +
     <CFD8D>DFA3@9=DCFC>@,?9C=3BB;FFE8FF0@5F9DEEBDFB..........
     (The paired read_1_2)
     @CL100089928L2C009R030_475184AAACACCAGACAATAC
      ACTGTAGAGAGCAGTTAAGACACTGGTAGGAGAGGAGAGGATTAAT........
     +
      FEBDFEEED@DD/FFFACEACEEFE9EFDCEEAB>7C.E6EEFFEFEFFEEFF;.....
      ################################################

The fastq format is correct, but what concerns me is that the barcode is added to the behind of reads name. The arcs results show that it cannot identify the barcode. I don't know what kind of fastq the arcs needs. Are there some problems?

(2) Then I mapped CHROMIUM_interleaved.fastq using bwa the the draft assembly.
         bwa index --> bwa mem --> samtools sort -n ..  > 10x.bam

(3) Then using ARCS:
         ./arcs -f Polished.Scaff10x_R2-renamed.fa -a AlignmentFile -s 98 -c 5 -l 0 -d 0 -r 0.05 -e 30000 -m 20-10000 -v > arcs.log

    In the AlignmentFile is the file of 10x.bam. Then the output of original.gv file has nothing. The log file shows that:
###############################################
.....
.....
       { "All_barcodes_unfiltered":0, "All_barcodes_filtered":0, "Scaffold_end_barcodes":0, "Min_barcode_reads_threshold":20, "Max_barcode_reads_threshold":10000 }
.....
.....
       Max Degree (-d) set to: 0. Will not delete any vertices from graph.
.....
.....
###############################################

Sorry for such long text. Could you please help with the problem?

Best~
Jing

**Comment by JhinAir** [comment]
Oh, I find it. The barcode seems need to be added by "_" following the reads name.

**Comment by lcoombe** [comment]
@JhinAir - Yes, as you are indicating, the issue with the read formatting that you have above is that you must have the form: ```@readHeader_barcode``` if you are embedding the barcodes in the read header names.
The barcode can also be read from the BX tag: 
```
@E00247:267:HMVT3CCXX:2:1207:19522:61714 BX:Z:AAACACCAGACAATAC-1
```
