### ISSUE TITLE
AGP file creation

### ISSUE THREAD

**Issue by shameem356** [bcgsc/arcs#45]
Hello arcs team,

We were able to make a very good genome assembly by using Tigmint+ARCS.Now we are looking to create a AGP file for our ARCS assembly.Is it possible to create a AGP file for ARCS assembly out put?

**Comment by lcoombe** [comment]
Hi @shameem356,

I'm glad to hear the Tigmint+ARCS worked well for your project!

In our group we use ```abyss-fatoagp``` to generate AGP files - This script is provided as part of [ABySS](https://github.com/bcgsc/abyss/tree/master/bin). I'd suggest using that perl script.

Example usage:
```
abyss-fatoagp -f agp_fasta  scaffolds_fasta > prefix.agp
```

Hope that helps!
Lauren
