### ISSUE TITLE
Problem with ARCS with or without Tigmint

### ISSUE THREAD

**Issue by agroppi** [bcgsc/arcs#50]
I working on a plant genome (~220 Mb)
My starting point is an phased assembly from Pacbio reads with Falcon and Falcon Unzip (774 contigs)

Important : I have renamed the contigs names by simple numeric identifier : 
```
>1
>2
...
>774
```

What I have done so far : 
1/ longranger basic on the reads.fastq from 10X genomics

2/ Tigmint correction with the following commands : 
```
samtools faidx draft.fa
bwa index draft.fa
bwa mem -t8 -p -C draft.fa reads.fq.gz | samtools sort -@8 -tBX -o draft.reads.sortbx.bam
tigmint-molecule draft.reads.sortbx.bam | sort -k1,1 -k2,2n -k3,3n > draft.reads.molecule.bed
tigmint-cut -p8 -o draft.tigmint.fa draft.fa draft.reads.molecule.bed
```
3/ When I try to run ARCS on the output from tigmint like with : 
`arcs -f draft.tigmint.fa -a file_of_bamfile -c 5 -e 30000 -r 0.05`

I have the following error : 
```
=> Reading alignment files... Mon Jan 21 11:07:40 2019
error: unexpected sequence: 1 of size 2459890+ draft.fa.c5_e30000_r0.05.tigpair_checkpoint.tsv draft.fa
/var/spool/slurmd/job108691/slurm_script: line 50: draft.fa.c5_e30000_r0.05.tigpair_checkpoint.tsv: command not found
```

4/ When I try to run ARCS without Tigmint (directly on my draft assembly) like this : 
`arcs -f draft.fa -a file_of_bamfile -c 5 -e 30000 -r 0.05`
I have this log : 

```
=> Reading alignment files... Mon Jan 21 10:15:51 2019
Warning: Skipping an unpaired read. Read pairs should be consecutive in the SAM/BAM file.
  Prev read: H9:1:HV2KYBBXX:6:1209:9090:3952
  Curr read: H9:1:HV2KYBBXX:6:2216:4482:43867
Warning: Skipped 1000000 unpaired reads.
Warning: Skipped 2000000 unpaired reads.
Warning: Skipped 3000000 unpaired reads.
...
Warning: Skipped 210000000 unpaired reads.
Warning: Skipped 210477149 unpaired reads. Read pairs should be consecutive in the SAM/BAM file.
{ "All_barcodes_unfiltered":1958917, "All_barcodes_filtered":1085640, "Scaffold_end_barcodes":1008556, "Min_barcode_reads_threshold":50, "Max_barcode_reads_threshold":10000 }

=> Pairing scaffolds... Mon Jan 21 10:39:45 2019

=> Creating the graph... Mon Jan 21 10:39:50 2019

=> Writing graph file... Mon Jan 21 10:39:50 2019

      Max Degree (-d) set to: 0. Will not delete any vertices from graph.
      Writing graph file to draft.fa.scaff_s98_c5_l0_d0_e30000_r0.05_original.gv...

=> Creating the ABySS graph... Mon Jan 21 10:39:50 2019

=> Writing the ABySS graph file... Mon Jan 21 10:39:50 2019
```

Thanks for your help

**Comment by lcoombe** [comment]
Hi @agroppi,
Are you making sure that you are sorting your alignments by read name ```samtools sort -n``` prior to running ARCS? 
Also, for (3), are you re-running the alignments after tigmint, before ARCS? 

If you haven't seen it already, our ARCS Makefile (Examples/arcs-make) is very useful for running the entire ARCS pipeline, with or without tigmint.

**Comment by agroppi** [comment]
Hi @lcoombe 
Thanks for your answer.
Yes I figured out after having submitted this issue the need of re-running the alignments after tigmint, before ARCS.
It's running. And I will sort the bam on the read name.

**Comment by lcoombe** [comment]
@agroppi - Great! I'll close this, but feel free to open another issue if you have any other questions.
