### ISSUE TITLE
arcs-make location

### ISSUE THREAD

**Issue by plw1080** [bcgsc/arcs#51]
Lauren wrote earlier:
>> As a side note we do have a Makefile (Examples/arcs-make) which runs the whole ARCS pipeline, >> taking the reads and the draft assembly as input. Even if you don't want to use the Makefile, I'd  
>> recommend taking a look to get an idea of the required steps.

Where do I find Examples/arc-make?

I have looked in: 
http://www.bcgsc.ca/downloads/supplementary/ARCS/
https://github.com/bcgsc/arcs/releases/download/v1.0.5/arcs-1.0.5.tar.gz

**Comment by lcoombe** [comment]
Hi @plw1080,
Here's the full link: https://github.com/bcgsc/arcs/blob/master/Examples/arcs-make

The path I provided is from the home page of this repository.

**Comment by plw1080** [comment]
Thank you; very helpful information but not clear about the "reads" arg.
arcs-make says: "reads read name [reads]. File must have .fastq.gz or .fq.gz extension"
But I have 4 channels of linked 10x reads:
marorg_S2_L001_I1_001.fastq.gz
marorg_S2_L001_R1_001.fastq.gz
marorg_S2_L001_R2_001.fastq.gz
...
marorg_S2_L004_I1_001.fastq.gz
marorg_S2_L004_R1_001.fastq.gz
marorg_S2_L004_R2_001.fastq.gz

**Comment by lcoombe** [comment]
Hi @plw1080 ,
You need to run ```longranger basic``` on those reads first to remove the barcode from the first read. Once you have run this, you should have an interleaved reads file with the barcode in the ```BX:Z:``` tag of the read header.
From the README on the home page of the repo:
```
Interleaved linked reads file (Barcode sequence expected in the BX tag of the read header or in the form "@readname_barcode" ; Run Long Ranger basic on raw chromium reads to produce this interleaved file)
```
Hope that helps!
Lauren
