### ISSUE TITLE
[E::bgzf_flush] File write failed (wrong size)

### ISSUE THREAD

**Issue by stevehilo** [bcgsc/arcs#52]
I'm running Arcs with Tigmint. It runs about 16 hours and crashes. I'm using Samtools-1.9. Longranger was used to create the interleaved barcoded file from a Chromium run. Taro.contigs.fa is assembled from Nanopore runs using Canu. I'm running on a single node with 20 cores and 128GB RAM. 
arcs-make arcs-tigmint draft=Taro.contigs reads=barcoded
End part of the error file is below:
[M::mem_process_seqs] Processed 573478 reads in 662.421 CPU sec, 81.837 real sec
[M::process] 0 single-end sequences; 573478 paired-end sequences
[E::bgzf_flush] [E::bgzf_flush] File write failed (wrong size)[E::bgzf_flush] File write failed (wrong size)
[E::bgzf_flush] File write failed (wrong size)
[E::bgzf_flush] File write failed (wrong size)
[E::bgzf_flush] File write failed (wrong size)
File write failed (wrong size)
[E::bgzf_close] File write failed
[E::bgzf_close] File write failed
[E::bgzf_close] File write failed
[E::bgzf_flush] File write failed (wrong size)
[E::bgzf_flush] File write failed (wrong size)

[E::bgzf_close] File write failed
[E::bgzf_close] File write failed
[E::bgzf_close] File write failed
[E::bgzf_close] File write failed
[E::bgzf_close] File write failed
samtools sort: failed to create temporary file "/tmp/Taro.contigs.barcoded.sortbx.bam.FfJGIn.0224.bam": No space left on device
samtools sort: failed to create temporary file "/tmp/Taro.contigs.barcoded.sortbx.bam.FfJGIn.0225.bam": No space left on device
samtools sort: failed to create temporary file "/tmp/Taro.contigs.barcoded.sortbx.bam.FfJGIn.0226.bam": No space left on device
samtools sort: failed to create temporary file "/tmp/Taro.contigs.barcoded.sortbx.bam.FfJGIn.0227.bam": No space left on device
samtools sort: failed to create temporary file "/tmp/Taro.contigs.barcoded.sortbx.bam.FfJGIn.0228.bam": No space left on device
samtools sort: failed to create temporary file "/tmp/Taro.contigs.barcoded.sortbx.bam.FfJGIn.0229.bam": No space left on device
samtools sort: failed to create temporary file "/tmp/Taro.contigs.barcoded.sortbx.bam.FfJGIn.0230.bam": No space left on device
samtools sort: failed to create temporary file "/tmp/Taro.contigs.barcoded.sortbx.bam.FfJGIn.0231.bam": No space left on device
time user=478289.20s system=444.58s elapsed=59684.76s cpu=802% memory=4870 job=bwa mem -t8 -pC Taro.contigs.fa barcoded.fq.gz
time user=952.14s system=103.13s elapsed=59684.72s cpu=1% memory=10 job=samtools view -u -F4
time user=3901.95s system=245.10s elapsed=59684.72s cpu=6% memory=6619 job=
make[1]: *** [Taro.contigs.barcoded.sortbx.bam] Error 1
make: *** [Taro.contigs.tigmint.fa] Error 2

**Comment by lcoombe** [comment]
Sounds good, Steven!
