### ISSUE TITLE
number of scaffolds == number of contigs

### ISSUE THREAD

**Issue by chen42** [bcgsc/arcs#54]
I am trying to improve rat reference genome rn6 with 10x data. I ran `longranger basic` on my R1 and R2 files to get a barcoded.fastq.gz file. I checked the file to make sure it has the BX:Z:barcode-1 after the @E in the fastq file (with a space in between). 
```
$ cat summary.csv 
barcode_diversity,bc_on_whitelist,num_read_pairs
1064967.05402,0.933687055596,394846319
```
I already ran  `tigmint` and have a rn6_after_tigmint.fa file. I also have a phased_possorted_bam.bam file from longranger. So far, I have done the analysis a few ways and got the same results: the scaffold.fa is basically the same as the rn6_after_tigmint.fa file, with one contig for one scaffold. I ran `assembly-stats` on both files and the stats are the same. The 
.assembly_correspondence.tsv file contains NA for all the rows in the last 3 columns. 

```
$ tail *correspondence.tsv
scaffold9553    7080    7080    f       NA      NA      NA
scaffold9554    5570    5570    f       NA      NA      NA
scaffold9555    3375    3375    f       NA      NA      NA
scaffold9556    2162    2162    f       NA      NA      NA
scaffold9557    8135    8135    f       NA      NA      NA
scaffold9558    3363    3363    f       NA      NA      NA
scaffold9559    7157    7157    f       NA      NA      NA
scaffold9560    6728    6728    f       NA      NA      NA
scaffold9561    1136    1136    f       NA      NA      NA
scaffold9562    7468    7468    f       NA      NA      NA
```

The analysis I've done:
1. arcs-make arcs draft=rn6_after_tigmint reads=myreads
2. pipeline_example.sh rn6_after_tigmint phased_possorted_bam.bam
3. runARCSdemo.sh also produced a links_c5r0.05e30000-l5-a0.9.scaffolds.fa that has the same assembly_stat as the hsapiens-8reformat.fa and NAs in the .assembly_correspondence.tsv file.

I am suspecting the barcodes are not being read into the pipeline but not sure how to check it. 
Any insights are highly appreciated!

arcs 1.0.5
tigmint 1.1.2
LINKS 1.8.6
longranger 2.2.2

**Comment by lcoombe** [comment]
Hi @chen42,
Have you been able to successfully run the test example (Examples/arcs_test-demo)?
Could you provide all of the commands that were run when you used the ```arcs-make``` Makefile?
Does your ```tigpair_checkpoint.tsv``` file have pairs of contigs listed? (Feel free to include a few lines of the file here if you aren't sure)

**Comment by chen42** [comment]
Hi, @lcoombe, 
Thank you very much for looking into my problem!
1. I installed arc in my homedir on a cluster. There is not enough diskspace in my home to run the test. So I copied the Example scripts to a project directory and ran the ```runARCSdemo.sh``` command and it did finish and produced the scaffold.fa file. I just checked the error log and found the following message:
```
Traceback (most recent call last):
  File "./makeTSVfile.py", line 96, in <module>
    readGraphFile(infile)
  File "./makeTSVfile.py", line 15, in readGraphFile
    with open(infile, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'hsapiens-8reformat.fa.scaff_s98_c5_l0_d0_e30000_r0.05_original.gv'
```

```The tigpair_checkpoint.tsv``` file is empty.


2. For my own data, my arcs-make script is very simple:        
```
cd /lustre/haven/proj/UTHSC0013/tigmint_data/arcs/
./arcs-make arcs draft=rn6_after_tigment reads=bnmale_barcode t=80
```
3. here are several lines of my tigpair_checkpoint.tsv:
```
10      r1021   r1661   1       100
10      f1661   f1021   1       100
10      r1021   r3226   1       100
10      f3226   f1021   1       100
10      f1025   f1037   1       100
10      r1037   r1025   1       100
10      f103    r1823   1       100
10      f1823   r103    1       100
10      f1057   f959    1       100
10      r959    r1057   1       100
....
....
10      r931    f935    1       100
10      r935    f931    1       100
10      r9495   r9536   1       100
10      f9536   f9495   1       100
10      f953    r955    1       100
10      f955    r953    1       100
10      f981    f989    1       100
10      r989    r981    1       100
```
Thanks!

**Comment by lcoombe** [comment]
Thanks @chen42,
For your own run, the fact that the tigpair checkpoint file isn't empty is a good sign - that means that some connections are being made, although the ones that you are showing aren't very supported - only 1 barcode supports each of those links. Are all the values in column 4 of your tigpair_checkpoint tsv ```1```?

Can you also post a few lines of your reads file, to just be doubly sure that the read headers are formatted correctly?

**Comment by chen42** [comment]
@lcoombe: I found the problem. My reads.fq.gz file was corrupted. So when I checked the file with `zcat`, the first few lines were OK  but there were not many reads in the file. The result is much better after fixing that issue, although most values in col 4 of the tigpair_checkpoint.tsv is still `1`:

```
$ cut -f 4 rn6_after_tigment_c5_m50-10000_s98_r0.05_e30000_z500.tigpair_checkpoint.tsv |sort |uniq -c |sort -rn |head
  54662 1
    398 2
    208 3
    174 4
    168 6
    168 5
    154 7
    150 8
    140 10
    134 9
```

Trying with a more accurate range for `m`:
```
$ cut -f 4 rn6_after_tigment_c5_m50-3000_s98_r0.05_e30000_z500.tigpair_checkpoint.tsv |sort |uniq -c |sort -rn |head
  54344 1
    398 2
    208 3
    178 4
    168 6
    164 5
    154 7
    150 8
    146 10
    132 9
```
I assume the value of `a` does not affect this. Any suggestion on which parameter I should try next? ***Thank you!***

**Comment by chen42** [comment]
I forgot to provide the first few lines of my reads file:

```
@E00247:397:HJ7YLALXX:8:1101:12195:19768_AAACACCAGCGATATA
TATACCACACACACACACCCCACACCATACCACACATATACCGCACAAACACACACCCCCCCCCCCATCCCGCACCGCTATCCCATATGCCCACCCCTGCCCGCCACTCATCCCCCGACCACACTTCA
+
FJJJJFAFFJJFJJ<J<JJJJJJJJJ<JJFFFFJJJFJJFAJ--A7---<FJ-<-7----7---7--77-7-A7------7A-A-77--------)7)))))))-)))7----7))))-))7------
@E00247:397:HJ7YLALXX:8:1101:12195:19768_AAACACCAGCGATATA
ATGTGTGGTATGGTGTGGGGTGTGTGTGTGTGGGATACTCGCAGTATATCGCTGGTGTTGAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGATCTCGGTGGTCGCCGTATCATTAAAAAGTAAGTGAGAGGTGGTGGGTGGTTGCGG
+
AAFAFJJJJJJJJJJJJJFJJJJJJJJJJJJJA--<A-<-----7<7-AAFA-7F7A---7777-<A-7F<F-7--AAAFFFJF-A7F-F<AA-A-<<JAFJ<AJ<)<-)A))----7--7-7----------77-)77)7-)))7--))7
@E00247:397:HJ7YLALXX:8:1101:2798:21456_AAACACCAGCGATATA
CCCACACACACACACAACACACAACACACACACACACAGGCACATACACACACACAACACACAGACACAACACACACAACACACACATACACCCACCACACACACACACAGCACACACAACACCCCCC
+
JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFJJFJJJJJ<JJJJJJFJJJFJJFJJJ-77FAJ<FJAJ-A7A7AJAAAF-F<-<F<AJFFFJ)FAF<FFJAJ<F--7<J7<-A--A-A-7--)

```

**Comment by chen42** [comment]
@lcoombe I tried several parameters. For my dataset, increasing e to 9000 has the largest effect on N50, when a is between 0.7 and 0.9. Thank you very much for your help in getting my error sorted out! I am closing this ticket.

**Comment by lcoombe** [comment]
@chen42 - Glad to hear you worked out the issues!
