### ISSUE TITLE
Supernova fasta output

### ISSUE THREAD

**Issue by pstokespmb** [bcgsc/arcs#57]
Hi there :).

I work on a highly heterozygous diploid organism. I have performed a Supernova assembly, and would like to use arcs+links to improve it. However, there are several fasta output options from supernova to choose from. I imagine I could either run arcs+links separately on both haplotype fasta files or once on the raw fasta file. Is there a "correct" way to do this?

**Comment by lcoombe** [comment]
Hi @pstokespmb,

Yes, you could do either approach! We usually use the `pseudohap` output format from Supernova to get a haploid assembly prior to scaffolding with ARCS, but it should also work fine to do the scaffolding on the haplotypes separately. I suppose it really just depends on if you want a haploid or diploid assembly in the end.

Hope that helps!
Lauren

**Comment by lcoombe** [comment]
@pstokespmb - I'll close this, but feel free to open another issue if you have any other questions!
