### ISSUE TITLE
unpaired reads issue

### ISSUE THREAD

**Issue by dcopetti** [bcgsc/arcs#59]
Hello,
When I run arcs
arcs -f genome_v2.1.fa barcoded_aln_sortbx.bam -s 100 -c 10 -l 5 -z 2000 -g arcs_out_1_abyss_dist.gv --tsv=arcs_out_1_graph.tsv --barcode-counts=arcs_out_1_reads_per_bc -b arcs_out_1
(5 Gb genome, N50 250 kb) the stdout file says that the bam file has unpaired reads, though it still completes the run (with an empty original.gv file):
Running: arcs 1.0.5
 pid 1222
 -c 10
 -d 0
 -e 30000
 -l 5
 -m 50-10000
 -r 0.05
 -s 100
 -v 0
 -z 2000
 --gap=100
 -b arcs_out_1
 -g arcs_out_1_abyss_dist.gv
 --barcode-counts=arcs_out_1_reads_per_bc
 --tsv=arcs_out_1_graph.tsv
 -a NA
 -f Rabiosa_genome_v2.1.fa
 Rab2.1_barcoded_aln_sortbx.bam

=> Getting scaffold sizes... Wed Apr 17 09:05:39 2019
=> Reading alignment files... Wed Apr 17 09:06:02 2019
Warning: Skipping an unpaired read. Read pairs should be consecutive in the SAM/BAM file.
  Prev read: ST-E00273:278:HGCTHALXX:6:1216:1529:19082
  Curr read: ST-E00273:278:HGCTHALXX:7:2204:21927:3260
Warning: Skipped 1000000 unpaired reads.
Warning: Skipped 2000000 unpaired reads.
[...]
Warning: Skipped 810000000 unpaired reads.
Warning: Skipped 810889008 unpaired reads. Read pairs should be consecutive in the SAM/BAM file.
{ "All_barcodes_unfiltered":3093694, "All_barcodes_filtered":1332396, "Scaffold_end_barcodes":1342415, "Min_barcode_reads_threshold":50, "Max_barcode_reads_threshold":10000 }
=> Writing reads per barcode TSV file... Wed Apr 17 11:13:12 2019
=> Pairing scaffolds... Wed Apr 17 11:13:17 2019
=> Creating the graph... Wed Apr 17 11:13:35 2019
=> Writing graph file... Wed Apr 17 11:13:35 2019
      Max Degree (-d) set to: 0. Will not delete any vertices from graph.
      Writing graph file to arcs_out_1_original.gv...
=> Creating the ABySS graph... Wed Apr 17 11:13:35 2019
=> Writing the ABySS graph file... Wed Apr 17 11:13:38 2019
=> Writing TSV file... Wed Apr 17 11:13:39 2019

=> Done. Wed Apr 17 11:13:40 2019

The alignment is done from Longranger basic reads that look like this:
@ST-E00273:278:HGCTHALXX:7:2211:7649:2610
AAGAAATTATCGATACGTTGGAGACGTATCAGCATCCCCAAGCTTAGTTCCTACTCGTCCCGAGTAGGTAAATGATAACAAAGATAATTTCTGAAGTGACATGCTATCATAATCTTGATCAATACTAT
+
JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFJAJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFJJJFFJJJJJJJJJJJJJJJJJJJAFJJJ7F
@ST-E00273:278:HGCTHALXX:7:2211:7649:2610
TATACATAATACATATGCTTTATTACTACCGTTGACAAAATTGTTTCTTGTTTTCAAAATAAAAGCTCTAGCACAAATATAGCAATCAATGCTTTCCTCTGCGAAGGGCCATTCTTCTACTTTTATGTTGAGTCAGTTCACCTACTCCTTT
+
AAFFFJJJJJJAJJJJJJJJJFJJJJJJJJJJJAFJFJJF7F<FJJJJJJJJJJ<JJJJJJJJJF-FJAAF7AAJ-FJJFJ-FFJJ<JJJJAAFJFJJJJAA<F-FFFAA<A-A7JFF<FAF-FFFAJFA-F7<F-7<-7F-<A-77-<<<
bwa and parsing:
bwa mem -t 22 -pC index barcoded.fastq.gz > barcoded_aln_2nd.sam
samtools view -@ 20 -h -b barcoded_aln_2nd.sam > barcoded_aln2nd.bam
samtools sort -@ 20 -tBX -o barcoded_aln_sortbx.bam barcoded_aln_2nd.bam
looking at the fastq, I wonder if the tag information got lost, and this can be the issue. The original fastq (before longranger) looked like this:
@ST-E00273:278:HGCTHALXX:6:1101:2615:1520 1:N:0:NGTGCAGA
NCGACCGGTAGAGCCAGGGTCCAATGCAGTTTTGCAGTGAGATGGGGCGGAATTGCGACGGGGGAACAGTGTTAATAATTTTGGGGAGGGACACTAGAAAGTCACGGTTATTACGTTGGTGGTTGATCGACACGTCAAAAAAAAGAGGAGA
+
#AAFFJF7-AFAJ-<JJJJJFJJJFJJJFJ-FFA7<A7-<FF<AJJ-77F<JJ7-7<J7<A--7<<7AA--<----7-<---77FJ--7--7-7777-A7F<AA-77F---77---7-7--A7---A---7-))-)-7-<-A7-7----)7
and had the 8-nt barcode. Did I lose it somewhere?
Odd, because in the reads_per_bc file I have them (though longer):
Barcode Reads
TACGGATCACTCACCT-1      23926
GTATCTTCAGATCTGT-1      20033
GTGCCTTCAGATCTGT-1      16253
GAACGCCCATTGGCGC-1      15480
GCCTGTTAGCCGTTAT-1      15442
Can anyone help me figure out where I am doing something wrong?
Thanks!

**Comment by lcoombe** [comment]
Hi @dcopetti ,

Just a suggestion - pasting code in triple back ticks is super helpful for readability.

For ARCS, we need the input BAM file to be sorted by name `-n` NOT by barcode -- I think you might be mixing up ARCS and tigmint there. I'd also suggest piping the processes to save you some large intermediate files:
```
bwa mem -t 22 -pC draft.fa barcoded.fastq.gz | samtools view -@ 20 -h -b |samtools sort -@20 -n -o draft.barcoded.name_sorted.bam
```

Have you taken a look at our `arcs-make` Makefile that can run the alignments and all ARCS steps for you? I find that's helpful for ensuring all the steps are completed correctly (Examples/arcs-make)

Also, the 16bp barcode sequences that are in the read headers post-longranger are what you want. The other indexes are the illumina barcodes, and aren't helpful for the purpose of ARCS (or tigmint, etc).

Hope that helps!
Lauren

**Comment by dcopetti** [comment]
yes, it was a sorting issue. All went good!

**Comment by lcoombe** [comment]
Glad that fixed it!
