### ISSUE TITLE
How is LINKS using .gv and .tsv files?

### ISSUE THREAD

**Issue by peterdfields** [bcgsc/arcs#6]
Hi,

I'm trying to use arcs pipeline and everything seems to run without error. I'm not getting any improvement on overall genome contiguity, but I'm not necessarily attributing this to the parameters themselves. What I don't understand quite yet is during the:

`runLINKS.sh`

step I'm not entirely understanding is how, given the script itself, the .gv and .tsv files are being used by LINKS. Is there an example log file available to determine if the program is functioning as expected?

**Comment by warrenlr** [comment]
The .gv file that ARCS outputs has to be converted in the .tsv file format LINKS understands.
For this, you must do the conversion using the makeTSVfile.py script. LINKS will then look for a file starting with a prefix (specified by the user, using -b.  eg. -b links_c5r0.05e30000  In this case, LINKS will look for a file called links_c5r0.05e30000.tigpair_checkpoint.tsv).

The content of the file looks like:

500	r17141	f964157	1	10
500	r964157	f17141	1	10
500	f17141	r964257	7	70
500	f964257	r17141	7	70
500	f17141	f964300	1	10
500	r964300	r17141	1	10
500	f17141	r964336	1	10
500	f964336	r17141	1	10
500	r17141	f965243	1	10 

Each row indicates a sequence pair.
The values are:
1) distance (arbitrarily set to 500 for ARCS). In a traditional LINKS k-mer based scaffolding, this is the distance between paired k-mers. This information is not used for ARCS scaffolding, but value must be there
2) first sequence ID.  ID preceded with orientation f=plus strand, r=minus strand
3) second sequence ID.   ID preceded with orientation f=plus strand, r=minus strand
4) number of supporting barcodes
5) estimates of the gap between the pair (arbitrarily set at 10 for ARCS, multiplicity of the 4th column.  eg. 5 supporting barcodes, 50 must appear in this column)

I suggest you follow all the steps as outlined here:
ftp://ftp.bcgsc.ca/supplementary/ARCS/docs/arcsDemoScripts/readme.md

The most common source of error stems from draft genome sequence IDs. To avoid confusion, it is best to renumber your draft assembly, as suggested in the readme.

**Comment by peterdfields** [comment]
Okay, this makes sense. Following along with read me and the associated scripts there seems to be some differences between what the runmeTSV.sh is creating, specifically outputs that look like: 

`ws77111_c3r0.05e30000.tigpair_checkpoint.tsv`

and then what the runLINKS.sh file is expecting (given your explanation), which is something like

`links_c3r0.05e30000.tigpair_checkpoint.tsv `

So then the output of runmeTSV.sh should just replace `ws77111` with` links`?

**Comment by warrenlr** [comment]
the name of the file is controlled by the user (you), so yes, you have to ensure that whatever you name your BASENAME.tigpair_checkpoint.tsv file after the makeTSVfile.py step, you specify its BASENAME in LINKS using -b BASENAME

--Rene

**Comment by JhinAir** [comment]
Hi,
When I used the BASENAME, links didn't recognize the BASENAME.tigpair_checkpoint.tsv. Its log file always get:

Running: ../../../../software/links_v1.8.6/LINKS [v1.8.6]
-f ../Emu.Polished.Scaff10x_R2-renamed.fa
-s empty.fof
-m -d
-d 4000
-k 15
-e 0.5
-l 5
-a 0.3
-t 2
-o 0
-z 500
-b ../Emu.Polished.Scaff10x_R2-renamed.fa.scaff_s-empty.fof_d4000_k15_e0.5_l5_a0.3_z500_t2_o0_r-_p0.001_x0_m-d_pid47296
-r
-p 0.001
-x 0

The -b fellow is not the file I provided. Could you please help with this?
Thank you very much!

Best~
Jing

**Comment by JhinAir** [comment]
Yes, I get it. The -m is not needed.
Best~

**Comment by lcoombe** [comment]
@JhinAir - Yes, you don't need to include -m when using LINKS with ARCS. If you are unsure about what parameters you should specify, take a look at ```Examples/arcs-make``` - This is a Makefile that you can use to run the different steps of the ARCS pipeline (and optionally Tigmint).
