### ISSUE TITLE
How can I decrease missing data in my draft genome

### ISSUE THREAD

**Issue by scintilla9** [bcgsc/arcs#60]
Hi, everyone

I'm now trying to scaffold my 10x data genomes, which were assembled  by Supernova 2.1.1. 

I tried both tigmint-arcs pipeline and arcs itself, not only to get a longer scaffold but also wants to decrease the gaps in my data. Thought the N50 scaffold did improved, the missing data (N) were all around a closed value. Such as 3.94%, 3.79% and 3.84% in the genomes,

Please kindly give me some suggestion about how to deal with this. Thanks!

**Comment by warrenlr** [comment]
Did you run any finishing tools on your post-arcs assemblies?
I recommend you use sealer using decreasing, multi-k values.

https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-015-0663-4

https://github.com/bcgsc/abyss/tree/master/Sealer

**Comment by scintilla9** [comment]
Many thanks!

No, I just stop at scaffolding so far.

I checked out Sealer. However I don't have other sequencing data like PE reads or MP reads from same sample.
Is this means I don't have ways to close the gap in genome?  
Cause from what I know, gapclosing needs another PE reads or MP reads, such like GapCloser and Sealer here.

**Comment by warrenlr** [comment]
...but you have 10x paired-end reads since you scaffolded with ARCS.  You should have ample coverage to run Sealer with that set.

**Comment by scintilla9** [comment]
Thanks for you advice.
I've ran Sealer these days by using the same reads that was used in ACRS. 
Sealer was successfully finished, and closing up about 25% gaps in my draft genome. 
I will try adjust my parameters to close more gaps.

Best

**Comment by warrenlr** [comment]
excellent, glad we could help!
