### ISSUE TITLE
Can't get the correct fastq format from longranger

### ISSUE THREAD

**Issue by sunnvor** [bcgsc/arcs#62]
Hi
I am sorry, this is more of a longranger issue than an ARCS issue, but since you recommend using longranger to get the correct format, I thought it would be appropriate to ask here. 
I can't seem to get the correct fastq format from longranger. Is there some option that I have missed? These are my commands:

./longranger mkfastq --run=/path/to/folder/171012_NS500347_0024_AHKMF5BGX3 --id=LinkedReads --samplesheet=/path/to/folder /samplesheet.csv --localmem=30 --localcores=16
./longranger basic --id Long --sample Herring --fastqs /path/to/folder/outs/fastq_path --localcores=32 --localmem=25

This ran without any problems, but my fastq file looks like this:

@NS500347:24:HKMF5BGX3:4:21611:18728:10214
CTCAACCACAATCACCCTCTACAACCAAAAAAAAAACAAACACAAAATCCAAACAAAAACACACAAAAACAAACAACTCACAACCACACATACAAACACACACGCAAAACAAAAAAAACTCGCCAGAA
+
/AAE/A<E/E/EE/</AA/E</E/</A///E/A/6///<//6///////////A////////////////</////E/<///////////////</////////</6///</////////6//////6
@NS500347:24:HKMF5BGX3:4:21611:18728:10214
CTTAATAAAAATTTAAGACACTGTCAGAATAACTGTTAGACCGTGACTAAAACAGACACTAACTGTGTGTTTGTATCACAATCAAAATATATATATATAACCTATTATCAAATATAAAAAGAGGAAAGATGTGTGTGTTTGTGTGTGTCAA
+
AAA///EA/AE6EA/6EEEEE//<EE/E////AAAEEEEE<A/E/E<AE///EE//6AE//EE/6A/AA/A<A///</<//6A//////<////</////<///A///6///////////A/<<////6/6</////AE/6/6/6//////

The second read is always longer than the first, so I guess the barcode is in this read. Am I correct? Is there an option in longranger basic that I can’t find, that places the barcode in the header?

Thanks in advanced.

Sunnvor

**Comment by sunnvor** [comment]
Turns out there was no problem. I only looked at the first few reads in the file, These reads didn't have a valid barcode because of low quality. Reads further down the file had better quality and did have barcodes in the header in the right format. 
Sorry about this.

**Comment by lcoombe** [comment]
@sunnvor - Thank you for posting your solution! And yes you're right - reads without a valid barcode (didn't match to the white list after barcode correction) don't get the `BX:Z` tag with the barcode in them. The first reads are a bit shorter because the barcode sequence is extracted from the beginning of that read.
