### ISSUE TITLE
Problems with arcs-make

### ISSUE THREAD

**Issue by majogomezhughes** [bcgsc/arcs#66]
Hi, I recently assembled a genome with supernova and then run tigmint on it. Now I am trying to run arcs to scaffold it, but when I do that I get the following error (I am running it with the pipeline arcs-make):

[E::sam_parse1] unrecognized type :
[W::sam_read1] Parse error at line 29609
[main_samview] truncated file.
echo draft.sorted.bam > draft_bamfiles.fof

After which it stops. How can I fix this?

Thanks!

**Comment by lcoombe** [comment]
Hi @majogomezhughes,

Could you please paste your full `arcs-make` command? Also any other errors/warnings in the log files. 

Thanks!
Lauren

**Comment by majogomezhughes** [comment]
Hi Lauren,

The arcs-make command is:

`./Examples/arcs-make arcs draft=draft reads=reads time=1 t=8 c=5 m=50-10000 z=500 s=98 r=0.05 e=30000 D=false dist_upper=false d=0 gap=100 B=20`

And by the log files do you mean the config.log file?

Thanks!

**Comment by lcoombe** [comment]
Thanks, @majogomezhughes.

The command looks just fine -- could you also send the result of `ls` in your directory, so I can double check that your arguments to `arcs-make` make sense with your files?

Also, by log I just mean the standard out of the pipeline.

**Comment by majogomezhughes** [comment]
Hi, the result of ls gives:

AUTHORS    Common     INSTALL      NEWS       ThirdParty     arcs.sh         bin          config.log     copy.o    draft.renamed.fa      draft.renamed.fa.pac  empty.fof    share
Arcs       DataLayer  Makefile     README     aclocal.m4     arcs1           compile      config.status  copy.sh   draft.renamed.fa.amb  draft.renamed.fa.sa   install-sh   stamp-h1
COPYING    Examples   Makefile.am  README.md  arcs-logo.png  autogen.sh      config.h     configure      depcomp   draft.renamed.fa.ann  draft.sorted.bam      missing      test-driver
ChangeLog  Graph      Makefile.in  Test       arcs.o         autom4te.cache  config.h.in  configure.ac   draft.fa  draft.renamed.fa.bwt  draft_bamfiles.fof    reads.fq.gz

But, I just looked at it and it seems that the error was because I moved the folder location. So I am re-running it right now. But did that error with sam can affect the results?


Thanks!

**Comment by lcoombe** [comment]
Were any of the files soft-links? Did that perhaps impact either the `draft.fa` or `reads.fq.gz` files?

It is possible that moving the folder location (mid-run I'm guessing?) could have impacted the run -- I'd re-start the alignments just in case.

**Comment by majogomezhughes** [comment]
Yes, I restarted it, but I get the same parse error from samtools, the pipeline continues after that and it finishes, but I don't know if this can be affecting the final result?

**Comment by lcoombe** [comment]
Yes, I’d worry that the error is a symptom that something went wrong in the alignment stage that could then be impacting your results. Would you be able to post the full standard out and standard error from the run?

**Comment by majogomezhughes** [comment]
Yes, the standard out is: 
`perl -ne 'chomp; if(/>/){$ct+=1; print ">$ct\n";}else{print "$_\n";} ' < draft.fa > draft.renamed.fa 
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_CTYPE = "UTF-8",
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("en_US.UTF-8").
bwa index draft.renamed.fa 
[bwa_index] Pack FASTA... 27.39 sec
[bwa_index] Construct BWT for the packed sequence...
[BWTIncCreate] textLength=7779819080, availableWord=559416368
[BWTIncConstructFromPacked] 10 iterations done. 99999992 characters processed.
[BWTIncConstructFromPacked] 20 iterations done. 199999992 characters processed.
[BWTIncConstructFromPacked] 30 iterations done. 299999992 characters processed.
[BWTIncConstructFromPacked] 40 iterations done. 399999992 characters processed.
[BWTIncConstructFromPacked] 50 iterations done. 499999992 characters processed.
[BWTIncConstructFromPacked] 60 iterations done. 599999992 characters processed.
[BWTIncConstructFromPacked] 70 iterations done. 699999992 characters processed.
[BWTIncConstructFromPacked] 80 iterations done. 799999992 characters processed.
[BWTIncConstructFromPacked] 90 iterations done. 899999992 characters processed.
[BWTIncConstructFromPacked] 100 iterations done. 999999992 characters processed.
[BWTIncConstructFromPacked] 110 iterations done. 1099999992 characters processed.
[BWTIncConstructFromPacked] 120 iterations done. 1199999992 characters processed.
[BWTIncConstructFromPacked] 130 iterations done. 1299999992 characters processed.
[BWTIncConstructFromPacked] 140 iterations done. 1399999992 characters processed.
[BWTIncConstructFromPacked] 150 iterations done. 1499999992 characters processed.
[BWTIncConstructFromPacked] 160 iterations done. 1599999992 characters processed.
[BWTIncConstructFromPacked] 170 iterations done. 1699999992 characters processed.
[BWTIncConstructFromPacked] 180 iterations done. 1799999992 characters processed.
[BWTIncConstructFromPacked] 190 iterations done. 1899999992 characters processed.
[BWTIncConstructFromPacked] 200 iterations done. 1999999992 characters processed.
[BWTIncConstructFromPacked] 210 iterations done. 2099999992 characters processed.
[BWTIncConstructFromPacked] 220 iterations done. 2199999992 characters processed.
[BWTIncConstructFromPacked] 230 iterations done. 2299999992 characters processed.
[BWTIncConstructFromPacked] 240 iterations done. 2399999992 characters processed.
[BWTIncConstructFromPacked] 250 iterations done. 2499999992 characters processed.
[BWTIncConstructFromPacked] 260 iterations done. 2599999992 characters processed.
[BWTIncConstructFromPacked] 270 iterations done. 2699999992 characters processed.
[BWTIncConstructFromPacked] 280 iterations done. 2799999992 characters processed.
[BWTIncConstructFromPacked] 290 iterations done. 2899999992 characters processed.
[BWTIncConstructFromPacked] 300 iterations done. 2999999992 characters processed.
[BWTIncConstructFromPacked] 310 iterations done. 3099999992 characters processed.
[BWTIncConstructFromPacked] 320 iterations done. 3199999992 characters processed.
[BWTIncConstructFromPacked] 330 iterations done. 3299999992 characters processed.
[BWTIncConstructFromPacked] 340 iterations done. 3399999992 characters processed.
[BWTIncConstructFromPacked] 350 iterations done. 3499999992 characters processed.
[BWTIncConstructFromPacked] 360 iterations done. 3599999992 characters processed.
[BWTIncConstructFromPacked] 370 iterations done. 3699999992 characters processed.
[BWTIncConstructFromPacked] 380 iterations done. 3799999992 characters processed.
[BWTIncConstructFromPacked] 390 iterations done. 3899999992 characters processed.
[BWTIncConstructFromPacked] 400 iterations done. 3999999992 characters processed.
[BWTIncConstructFromPacked] 410 iterations done. 4099999992 characters processed.
[BWTIncConstructFromPacked] 420 iterations done. 4199999992 characters processed.
[BWTIncConstructFromPacked] 430 iterations done. 4299999992 characters processed.
[BWTIncConstructFromPacked] 440 iterations done. 4399999992 characters processed.
[BWTIncConstructFromPacked] 450 iterations done. 4499999992 characters processed.
[BWTIncConstructFromPacked] 460 iterations done. 4599999992 characters processed.
[BWTIncConstructFromPacked] 470 iterations done. 4699999992 characters processed.
[BWTIncConstructFromPacked] 480 iterations done. 4799999992 characters processed.
[BWTIncConstructFromPacked] 490 iterations done. 4899999992 characters processed.
[BWTIncConstructFromPacked] 500 iterations done. 4999999992 characters processed.
[BWTIncConstructFromPacked] 510 iterations done. 5099999992 characters processed.
[BWTIncConstructFromPacked] 520 iterations done. 5199999992 characters processed.
[BWTIncConstructFromPacked] 530 iterations done. 5299999992 characters processed.
[BWTIncConstructFromPacked] 540 iterations done. 5399999992 characters processed.
[BWTIncConstructFromPacked] 550 iterations done. 5499999992 characters processed.
[BWTIncConstructFromPacked] 560 iterations done. 5599999992 characters processed.
[BWTIncConstructFromPacked] 570 iterations done. 5699999992 characters processed.
[BWTIncConstructFromPacked] 580 iterations done. 5799999992 characters processed.
[BWTIncConstructFromPacked] 590 iterations done. 5899999992 characters processed.
[BWTIncConstructFromPacked] 600 iterations done. 5999999992 characters processed.
[BWTIncConstructFromPacked] 610 iterations done. 6099999992 characters processed.
[BWTIncConstructFromPacked] 620 iterations done. 6199999992 characters processed.
[BWTIncConstructFromPacked] 630 iterations done. 6299999992 characters processed.
[BWTIncConstructFromPacked] 640 iterations done. 6399999992 characters processed.
[BWTIncConstructFromPacked] 650 iterations done. 6499999992 characters processed.
[BWTIncConstructFromPacked] 660 iterations done. 6599999992 characters processed.
[BWTIncConstructFromPacked] 670 iterations done. 6699999992 characters processed.
[BWTIncConstructFromPacked] 680 iterations done. 6799999992 characters processed.
[BWTIncConstructFromPacked] 690 iterations done. 6899999992 characters processed.
[BWTIncConstructFromPacked] 700 iterations done. 6999999992 characters processed.
[BWTIncConstructFromPacked] 710 iterations done. 7099999992 characters processed.
[BWTIncConstructFromPacked] 720 iterations done. 7194909112 characters processed.
[BWTIncConstructFromPacked] 730 iterations done. 7279263032 characters processed.
[BWTIncConstructFromPacked] 740 iterations done. 7354232984 characters processed.
[BWTIncConstructFromPacked] 750 iterations done. 7420862456 characters processed.
[BWTIncConstructFromPacked] 760 iterations done. 7480078888 characters processed.
[BWTIncConstructFromPacked] 770 iterations done. 7532706584 characters processed.
[BWTIncConstructFromPacked] 780 iterations done. 7579478184 characters processed.
[BWTIncConstructFromPacked] 790 iterations done. 7621044888 characters processed.
[BWTIncConstructFromPacked] 800 iterations done. 7657985480 characters processed.
[BWTIncConstructFromPacked] 810 iterations done. 7690814328 characters processed.
[BWTIncConstructFromPacked] 820 iterations done. 7719988648 characters processed.
[BWTIncConstructFromPacked] 830 iterations done. 7745914840 characters processed.
[BWTIncConstructFromPacked] 840 iterations done. 7768954072 characters processed.
[bwa_index] 3339.32 seconds elapse.
[bwa_index] Update BWT... 19.53 sec
[bwa_index] Pack forward-only FASTA... 20.97 sec
[bwa_index] Construct SA from BWT and Occ... 948.82 sec
[bwt_gen] Finished constructing BWT in 846 iterations.
[main] Version: 0.7.4-r385
[main] CMD: bwa index draft.renamed.fa
[main] Real time: 4363.128 sec; CPU: 4356.036 sec
sh -c 'bwa mem -t8 -C -p draft.renamed.fa reads.fq.gz | samtools view -Sb - | samtools sort -@8 -n - -o draft.sorted.bam'
[M::main_mem] read 529802 sequences (80000102 bp)...
[M::mem_pestat] # candidate unique pairs for (FF, FR, RF, RR): (1225, 75010, 413, 1208)
[M::mem_pestat] analyzing insert size distribution for orientation FF...
[M::mem_pestat] (25, 50, 75) percentile: (114, 205, 331)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 765)
[M::mem_pestat] mean and std.dev: (223.54, 146.81)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 982)
[M::mem_pestat] analyzing insert size distribution for orientation FR...
[M::mem_pestat] (25, 50, 75) percentile: (279, 351, 451)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 795)
[M::mem_pestat] mean and std.dev: (369.59, 131.34)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 967)
[M::mem_pestat] analyzing insert size distribution for orientation RF...
[M::mem_pestat] (25, 50, 75) percentile: (62, 164, 396)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 1064)
[M::mem_pestat] mean and std.dev: (187.22, 209.01)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 1398)
[M::mem_pestat] analyzing insert size distribution for orientation RR...
[M::mem_pestat] (25, 50, 75) percentile: (123, 202, 317)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 705)
[M::mem_pestat] mean and std.dev: (220.26, 140.57)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 899)
[M::mem_pestat] skip orientation FF
[M::mem_pestat] skip orientation RF
[M::mem_pestat] skip orientation RR
[M::worker2@4] performed mate-SW for 247305 reads
[M::worker2@0] performed mate-SW for 250703 reads
[M::worker2@3] performed mate-SW for 250720 reads
[M::worker2@5] performed mate-SW for 250629 reads
[M::worker2@6] performed mate-SW for 249217 reads
[M::worker2@2] performed mate-SW for 252935 reads
[M::worker2@7] performed mate-SW for 257253 reads
[M::worker2@1] performed mate-SW for 257840 reads
[E::sam_parse1] unrecognized type :
[W::sam_read1] Parse error at line 29609
[main_samview] truncated file.
echo draft.sorted.bam > draft_bamfiles.fof
/hpcfs/home/mj.gomez12/files/Secuencias/Assembly/arcs4/arcs/Arcs/arcs --bx -v -f draft.renamed.fa -a draft_bamfiles.fof -c 5 -m 50-10000 -s 98 -r 0.05 -e 30000 -z 500 -d 0 --gap 100 -b draft_c5_m50-10000_s98_r
0.05_e30000_z500
Running: arcs 1.0.6
 pid 52891
 -c 5
 -d 0
 -e 30000
 -l 0
 -m 50-10000
 -r 0.05
 -s 98
 -v 1
 -z 500
 --gap=100
 -b draft_c5_m50-10000_s98_r0.05_e30000_z500
 -g draft_c5_m50-10000_s98_r0.05_e30000_z500.dist.gv
 --barcode-counts=NA
 --tsv=NA
 -a draft_bamfiles.fof
 -f draft.renamed.fa

=> Getting scaffold sizes... Wed Jul 31 19:46:09 2019
Saw 29608 sequences.

=> Reading alignment files... Wed Jul 31 19:46:23 2019
Reading alignments: draft.sorted.bam
{ "All_barcodes_unfiltered":0, "All_barcodes_filtered":0, "Scaffold_end_barcodes":0, "Min_barcode_reads_threshold":50, "Max_barcode_reads_threshold":10000 }

=> Pairing scaffolds... Wed Jul 31 19:46:23 2019

=> Creating the graph... Wed Jul 31 19:46:23 2019

=> Writing graph file... Wed Jul 31 19:46:23 2019

      Max Degree (-d) set to: 0. Will not delete any vertices from graph.
      Writing graph file to draft_c5_m50-10000_s98_r0.05_e30000_z500_original.gv...

=> Creating the ABySS graph... Wed Jul 31 19:46:23 2019

=> Writing the ABySS graph file... Wed Jul 31 19:46:23 2019


=> Done. Wed Jul 31 19:46:23 2019
python /hpcfs/home/mj.gomez12/files/Secuencias/Assembly/arcs4/arcs/Examples/../Examples/makeTSVfile.py draft_c5_m50-10000_s98_r0.05_e30000_z500_original.gv draft_c5_m50-10000_s98_r0.05_e30000_z500.tigpair_chec
kpoint.tsv draft.renamed.fa 
ln -s draft_c5_m50-10000_s98_r0.05_e30000_z500.tigpair_checkpoint.tsv draft_c5_m50-10000_s98_r0.05_e30000_z500_l5_a0.3.tigpair_checkpoint.tsv
LINKS -f draft.renamed.fa -s empty.fof -b draft_c5_m50-10000_s98_r0.05_e30000_z500_l5_a0.3 -l 5 -a 0.3 -z 500 
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_CTYPE = "UTF-8",
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("en_US.UTF-8").

Running: /hpcfs/home/mj.gomez12/.conda/envs/arcs-env/bin/LINKS [v1.8.6]
-f draft.renamed.fa
-s empty.fof
-m 
-d 4000
-k 15
-e 0.1
-l 5
-a 0.3
-t 2
-o 0
-z 500
-b draft_c5_m50-10000_s98_r0.05_e30000_z500_l5_a0.3
-r 
-p 0.001
-x 0

----------------- Verifying files -----------------

Checking sequence target file draft.renamed.fa...ok


Scaffolding mid-point files:
draft_c5_m50-10000_s98_r0.05_e30000_z500_l5_a0.3.tigpair_checkpoint.tsv
draft_c5_m50-10000_s98_r0.05_e30000_z500_l5_a0.3.simplepair_checkpoint.tsv
detected; LINKS will skip contig pairing and use info from files instead : Wed Jul 31 19:46:31 -05 2019

Reading sequences from draft.renamed.fa : Wed Jul 31 19:46:31 -05 2019

done.
Reading sequence pairs from draft_c5_m50-10000_s98_r0.05_e30000_z500_l5_a0.3.tigpair_checkpoint.tsv : Wed Jul 31 19:46:40 -05 2019

done.
Building scaffolds : Wed Jul 31 19:46:40 -05 2019

done.
Building .gv graph : Wed Jul 31 19:46:41 -05 2019


=>Scaffolding ended : Wed Jul 31 19:46:41 -05 2019
Scaffolds layout in: draft_c5_m50-10000_s98_r0.05_e30000_z500_l5_a0.3.scaffolds
Scaffold graph in: draft_c5_m50-10000_s98_r0.05_e30000_z500_l5_a0.3.gv


=>Making FASTA file : Wed Jul 31 19:46:41 -05 2019
Scaffolds FASTA in : draft_c5_m50-10000_s98_r0.05_e30000_z500_l5_a0.3.scaffolds.fa


=>Wrote correspondence file tracking LINKScontigID <=> OriginalContigNames : draft_c5_m50-10000_s98_r0.05_e30000_z500_l5_a0.3.assembly_correspondence.tsv

Scaffolding executed normally Wed Jul 31 19:46:57 -05 2019
/hpcfs/home/mj.gomez12/.conda/envs/arcs-env/bin/LINKS [v1.8.6] terminated successfully on Wed Jul 31 19:46:57 -05 2019
rm draft_c5_m50-10000_s98_r0.05_e30000_z500_l5_a0.3.tigpair_checkpoint.tsv`


And I don't know what do you mean by standard error? I thought that was in the out?

**Comment by lcoombe** [comment]
Whether your standard output and error are separated just depends on how you kept the output (ie. if you piped `1>` to one file and `2>` into another, or did `&>` to put all in one file, or if you just printed to the console. Regardless, this log is fine.

It is hard to know exactly what is going on, but there is something wrong with the BWA output at line 29609 which `samtools` seems to be unable to parse. You'll have to do some troubleshooting to figure out what that is. Some suggestions:
1. Feel free to show the first few lines of your read files here so we can double check that formatting is OK.
2. Figure out what about that BWA output line doesn't adhere to the proper formatting for samtools. You could do this by subsetting your reads, and trying the BWA mem step outputting to a SAM file so you can actually look at the line the is causing issues.
3. Double check that the reference file and the renamed version both have the same number of lines/stats, and take a peek to make sure the formatting looks OK (just to make sure that those perl warnings didn't cause issues)

Sorry I can't be more specific with how to solve the problem -- I haven't seen this issue before and this issue is more of an alignment problem vs. specific to ARCS.

**Comment by majogomezhughes** [comment]
The read files look like this:

`@E00438:380:HK57WCCXY:6:1101:8430:1397 1:N:0:NAAGTGCT
NGACACAGTAGCCTTATCCTAGGTCAGGAGGAGGAGGAGGAGCAGGAGGAGCAGGAGGAGCAGGAGGAGGTGAAGGAGGAGGAGGCGGAGCAGGAGGAGGAGGAGGAGGAGCAGGAGGAGCAGGGGATGCAGGAGGAGGAGGAGGAGGCAG
+
#AAF<A7AAJJA-FJJJFFAAAF-F<AJ-7F-7<JJAAF7FJJA-FF7A<JFFJJFAA7J7AFAAJA77--7-777-FJ-FF-A---7-7--7F7--JFJ-FF<-F-7F)F)-<<)AJ-F))A<)A7)7)-7)77A-)<)7<7AA)7--)A
@E00438:380:HK57WCCXY:6:1101:12317:1415 1:N:0:NAAGTGCT
NAATTGCCAGTTAACCGTACAGTTATGGCCTCAATTAACCAATAAAAATAAACAGAATGGCAGAATGGATCAAAAAACAACATCCAACCATATGCAGTCTACAAGAAACCCATCTAACCCAAAAGGATATTCAAAGACTGAAAAACCAAGG
+
#AAFFJ7F7F<FJ<JFF<J7AA<-FJ<--7-AF-F7-<7-<FF-7FF--<<<<--A-<-<<A<7J-A<<FFFF<7-7-AF-F<-AFJJ-F-<<FF-7<77FFFF77-FFFAF-)-AA--<FFFJ<77-F-<AAAA---7-7FJF---AF7)
@E00438:380:HK57WCCXY:6:1101:14306:1415 1:N:0:NAAGTGCT
NGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGGATAGTGTTAGGGTTAGAGTTCGGGTTAGGGGTCGAGTTAGGGATAGGTTTCGCGTAAGGGGTAGTGTTAGGGTGAAGGTTAGAATGAGACAGAGGTGTG
+
#AAFAFFJJJFJJFJJJJJFJJF7AJFJ-FFJFF<FJJFF-FJ<<F<<<F---<<7-A--7FFJ-7AJ-7--77-777-<7--7---7A-7--77--7----7--7---7-7-7))-7---7---)7-7---7------<-----7)-)-7
@E00438:380:HK57WCCXY:6:1101:23926:1415 1:N:0:NAAGTGCT
NCTGCTCTCAGCACATATTGAGGGGCCCAGGGATCATGGACTGAAACCTCTGAAAAGATGATCCACAATAAACATGTCTTCATTTTCAGTTGTTTATCGCTGATATATTGTTAGAGGAATGGAGAGATGACTAACACAAGAAGATTAAAGG
+
#AAAAF7AFJJ7<7<FAAF7-FJFFA-F-7F-7<7FJFJJAJJFJJF<<7<77-<7-<FJ7AF7--<-77F-A-F---7A7---777-AFA--FFAA<F--7AF7--7FAF-7F7F-JFJJJ--7F--<-<F<---77-777A<-<F---<
@E00438:380:HK57WCCXY:6:1101:21988:1432 1:N:0:NAAGTGCT
NACACGAGTTCACCTCCCATTGCGAGCAGGAGGAGGAGCAGGAGGAGGAGGAGCAGGAGGAGGAGCAGGAGGAGGAGCAGGAGGAGCAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGCAGGAGGAGGAGCAGGAGGAGGGGGA
+
#AA<FJF<-AF-<FFFJFJJJ-7<7J7FAJJAFAAAFFJJJJJ7<AA-FF7JJ7--A-FJJFJJJA<J<FFJJJAA-7F-F<AFJJ<-7F---AFJ-7F---7F-)--7FF)<A)-A)7AAA77A)))77<)<))-A)77A)7<-7-)))-
@E00438:380:HK57WCCXY:6:1101:24485:1432 1:N:0:NAAGTGCT
NATCGTAAGGGATAAGGGGAGGAGGAGGAAGGGGAGGAGGAGGAACGGGCAGGGAGGAAGGGGAGGAGGAGGAGGAAGGGGAAGAAGAGGAGGGGGGGGAGGTGGAGGATGAGGAAGAGGGGGCGGATGAAACGGAGAAGGAGGAGACTGA
+
#AAAFFF7-FFFJJ<FJJJJJAJJF7-F-F7FF<-A--77FAJJJA-AA--777---A<JFAJ-7<-A7-77-----<77<F-7-7-AAA-7----77-A---)-)--)-7-7<--7-77)A-)---))----7--77-----777-)-7-
@E00438:380:HK57WCCXY:6:1101:17655:1450 1:N:0:NAAGTGCT
NGACACAGTTCTCAAGTATCATTCCCATAATGAAATGCCACAGTTAGATACATCCACATGATTTGCCATTATTATATCAATAATCGTCTCCTTGTTCCTATTCTTCAAACCGAAAATCTCAACCCACTTATTTAATCTAGAACCTAAAACA
+
#AAFFJJFJJF<FJJJJFJFFJFFJJAJJJF-JJFJJJJJFAAFFJJJJJJJJJ<<<<JAFJJJF-FJF-JJJ<A-AAAA7-F-AAJ<J7FF<JF<AJJ-7A-AA-7FJJJJA-AJAFFAAFJAJJA)FFJJF-<FAFJJJJJJ<F<F<<J
@E00438:380:HK57WCCXY:6:1101:18182:1450 1:N:0:NAAGTGCT
NCACGTTGTAAATACGCTGGAGCATGTTTCAGCACACTGCTCTTGATCTTAGTGCTGACAACCGCTCACACAGACATTCTGTGCTTAGTCTTACCTTGGTATCGGAGGAAGAGCTTGGAATAAAAATTAGTAGGACAACAGCAAATGTCAC
+
#AAFFJ-FJJ<-AJJJJAA7J-AJJJJJJJJFFFJJ<FJJFJJ-7FA77JJ7JFF<AFJJJFF-F-AJ7AFJJJJ7AJJFJJJFJJ7JFFJJ-7A-FF<FJFFF<<--AAFJJJJJFF7FFJAFAFFFJJJJ7-<FA-FFJJJFAJA77-7
@E00438:380:HK57WCCXY:6:1101:18304:1450 1:N:0:NAAGTGCT
NCCGGTTAGGTAGTTAGGGAAGATCCTAGAGTGTTTTAAGCAGGAAAGTGTAATAATTTCATGTATGTTTTAAAAAGATCAAACTAGCTGATGTGAGGGAAGAGACATCAGAAGAACAAGAGCTGAAAGTGCAGAAGGCTATGCCAGTAGT
+
#AAFAFAFJJJAJFJJJJJ<JAFFFJJ7JAJJJJJJF<J<FJJF7FFA<JJ-AJ-F<7AFJJJJJJJFFJJ<JJJ-7AF7J-F-7FFF7AFFJJJ-FFJ7AJFJ-A-<AFJFJJJJFJ<JFJJAJA<7<AFFAF7<<FFJJJJJ<FAFJJF
@E00438:380:HK57WCCXY:6:1101:18690:1450 1:N:0:NAAGTGCT
NCGCTAGAGGTGACCATGGAGGAGGAGGAGATGGAGGAGGAGGAGATGGAGATGGAGGAGGAGGAGATGGAGAAGGAGGAGGAGGTGGAGGAGGAGATGGAGGAGGGGGAGACGGAGGAGGAGGAGATGGGGGCGGCGGAGGTGTAGGAAG
+
#AAFFJ<-FJA<J7<AJJJ-FJAFJFFJAFFJJFFJF<7A-FJA-FAAJJFFAAJ<FAAJJAF-7A<F<-AA-FF<FAFAJ<-7--A<77A7-7F<-7---77)7F-77-7<)-7)-7AJJFF))<----)7<))))-)))--<--7----
@E00438:380:HK57WCCXY:6:1101:19380:1450 1:N:0:NAAGTGCT
NTCGTGCGTTCAGCGCGAATCCATCCACCCATCCATCCATGCATCCACCCATCCAAGCATCCACCCATCCATGCACCCATCCATCCATCCACCCATCCATCCAGACATCCATCCATCCATCCACCCACCCATCCAAACACCCATTCATCGA
+
#AAFFF-AAJ<FFJJFJJFF77F<JFFFJFFJA-AJ7-<<-AJF-AAAAFF7AF7--77F-AAAAFJJF<FJ-7-77A<-F-<7AJ-AA<777F<-AF-FJAF---7-----FJF<-A7--)-AF)))--)-)77-----<AJ7-A7A---
@E00438:380:HK57WCCXY:6:1101:22729:1450 1:N:0:NAAGTGCT
NAGTCAGCAGCTTCGGGAAAGCAACCCTCCCTAAATCATTCCAGGAGGCAAGTATTACTGTCAGTATCACTAATGAACATTGATGCAAAAATTCTCAATAAAATACTGGCAAATAGAATGCAGTAAATCATCAACAAGATTATACATCATG
+
#AAAFJF<JJJFA<F<F7FJ7A<-FJ<JJ7FJJ<JJJFFF-FJ-77A-AJF7<F<J--AFAFJ-<--FAAJ7JAF7-FJFJ<JFJAJFJFJF-7A-AFFFAJJ-77-<FJJFJFJJJJFJ7J<-<FJ7-FFA7---<7FFFF-<A7-7-7-
@E00438:380:HK57WCCXY:6:1101:20222:1467 1:N:0:NAAGTGCT
NGGAGCTAGAATCGGCAGAACGTTACGTTCTGTGAGTAGTATGAGAGAGTTTATAGAGAGGCTTTAAATGGGAGAGCTCATGGAGGAGGATTTGCAGGGTTCCTGTTAGACAACTGCCCTGAGACACTGGACAGGCAGCCAAAGACGGGCA
+
#AAAFFJF7JAAAFJJJ<J<77<-FJ-FJJJJFAJJJJJ7JJJ<FJJFAA-A7JJ--AFJJJJJJJJJJFJ7JJJ7-7FJJJFFJF<JJ<<AFJJ7JJJJFF-FAJ-FJJJAJJJJJFJJJJF<FF7<FJF7-AF<AA-FFJJJAA7FJ-)
@E00438:380:HK57WCCXY:6:1101:23997:1467 1:N:0:NAAGTGCT
NACTCTATCTGATACGGGAAAGCATAGAACTTTCTAGGAAATATGAAGGCAACTATAAGTATACTATTTCCTTCCATTAGTTTATATATGCTTATATGGATCAGACTTACATTTTTTCCCTTCAGATATTTTCTAAACCAGCCAAGTATGC
`

And both files have this formatting:

`>1
TTCTGGGAGGTGGTGGAACTTTAAGAGTTGGAGCCCAGTGGGAGTGTATCCTTGAGGGAACAGTGGGACTCCATCTCTTCCTCCTCTCCTTTTCAATTCCCAGGGCTGAGGTTAAGGGTTTGGTATGTGCTGCTACCTTGCTGTGCTGCCTTGCCATAGGCCCAACAGTGACAGGGTCAACTAGCCACAGATTGACAGATTCACACACA
ATTAGGTCAAGACAACCAAGGATAATCACCCTTCTTTAAACAGTAGTCTCCATTCCTTAAAATGGTATTAAATGTGTAATCATGGAGCCATAGCTCATCAAATTCACAGTTCCTCAAACCCTGAAGGGCAAGAACTGCACAATTACAGATCGCTGTGCTGTTGCCCTAGATGTCAACCTAATCAAGAATGAGGAAAATTGTATGTATAT
GGAGCTAAACAGGATTACAATCTGGGAAAACACCGATTGGAGCAGTCTTGAACATGCCCTCTGAAAATGCTTTACAAAGTATGACAGTATTTATAGCTTCGAGCCATGAAGAATAGTTGAAAATTTCATCACCTGTTAAGAATTATGACTGATGCTGATTCGGGTTAAACTGTCTTGGCAGAAAAGAGTTAAGTGGCCAGATGTGATGA
CACACATCTGTGATCATAGCACTCTGGAGGCTGAGACACCAGGATCTCTGGGAGTTTGAGTCCATCTTGGACTACAAATTGAGTTAAAGATCAGTCTGAACTCATAGTGAAACTTCGTCTGAAAGAGACAAAATGAAAGAGGAGAGAGAGAGAGAAACGAGTTAGGTGTGATAAATTTGTTTGAGAATATACGTGAAATCTGATTAGCA
TCCAGCTCTGTTTTAAGTGCCTTGAATCAATACCACTCCGTGTAGACTTTTTTCCCTGAGACCAGTTTTTCTTAGAATTCAGCCTACCACCATTTCCTTTCAGACAAACATTTAAAATCAGAAAGACAATTTTCATTCAAAAAGTTCACTTTCCAGCAAAAACAAAAACAAACAAACAAAAAAACCCAGGAAAATATATTACCAGTTTT
AAGGTAATATGAAT`

This is different from the supernova output, but I don't know if this can be causing any issues? 
If I don't put the -C option in bwamem it works fine, but I would assume that this will not let arcs perform as well?

Thanks!

**Comment by lcoombe** [comment]
I hope you don't mind me formatting your comments -- I just find it easier to look at code/files with triple back ticks.

Looks like you are using the raw chromium reads instead of the reads post-longranger? You need the barcode sequence to be in the `BX:Z` tag of the read header, but in those reads I believe the barcode is still in the first reads.

**Comment by majogomezhughes** [comment]
Ok, I will try that! Thank you!

**Comment by lcoombe** [comment]
Great! I'll close the issue for now, but feel free to re-open if you still have issues after using the post-`longranger basic` data. 
By the way, tigmint also requires the reads to have the barcode extracted to the read header like ARCS, so you should also re-run tigmint once you have that processed reads file.
