### ISSUE TITLE
It is the same readme file!

### ISSUE THREAD

**Issue by sunnycqcn** [bcgsc/arcs#72]
Hello,
It is a good software. But commands help file show the same instruction in arcs-tigmint and arks-tigmint. The detail is as following.
My question is if arcs-tigmint run tigmint and arcs and  arks-tigmint run tigmint, arcs, and arks.
Usage: ./arcs-make [COMMAND] [OPTION=VALUE]...
    Commands:

        arcs            run arcs in default mode only, skipping tigmint
        arcs-tigmint    run tigmint, and run arcs in default method with output of tigmint
        arks            run arcs in kmer mode only, skipping tigmint
        arks-tigmint    run tigmint, and run arcs in default method with output of tigmint
        help            display this help page
        version         display the software version
        clean           remove intermediate files
Thanks,
Fuyou

**Comment by lcoombe** [comment]
Hi Fuyou,

ARCS and ARKS perform the essentially the same task (scaffolding assemblies), just in slightly different ways. Both of them scaffold assemblies using linked reads, and actually use a lot of the same code (hence why we merged the repositories recently). ARCS just uses read alignments to assign barcodes to contigs, and ARKS uses exact kmer matching.

So `arcs-tigmint` will run Tigmint, then ARCS. `arks-tigmint` will run Tigmint, then ARCS in kmer mode (ARKS).

I can see how that typo in the Makefile is confusing -- I fixed that in 4f76236, so I hope it's more clear now.

Thank you for your interest in ARCS!
Lauren

**Comment by sunnycqcn** [comment]
Thanks,
Fuyou

发自我的 iPhone

**Comment by sunnycqcn** [comment]
Hello Lauren,
By the way, I have read about arks and arcs instruction. I am not still clearly understand what they are different.
Currently, I have 402,000,000 10x linked reads and 1.6Gb genome size with 6000 scaffolds. I want to furthermore scaffold my assembly with ARCS. Based on your experience in ARCS, which model is better, arcs-tigmint or arks-tigmint?
Thanks,
Fuyou

**Comment by lcoombe** [comment]
Hi Fuyou,

For that data, I think using `arks-tigmint` would work well. You will get very similar results from running ARCS in default mode or kmer mode (ARKS), but the kmer mode is much faster, as it doesn't require read alignments.

ARKS doesn't scale as well with very fragmented assemblies or large genomes, but your genome is relatively small and the assembly seems to be fairly contiguous.

Hope that helps!
Lauren
