### ISSUE TITLE
About contig length & Scaffold length

### ISSUE THREAD

**Issue by EugeneKim76** [bcgsc/arcs#78]
Dear all,
To my understanding, arcs & links are used for just contig ordering.
However, I found that total bases of scaffolds is slight different from that of  contigs before scaffolding.
Is there any process that makes such difference during scaffolding?
Best,

**Comment by lcoombe** [comment]
Hi @EugeneKim76 ,

Yes, ARCS and LINKS are used to order and orient contigs into larger scaffolds.

Did you include the `N`'s when you were counting the bases, or use any sort of length cut-off? ARCS will introduce lengths of `N`'s between merged contigs -- the gap length is 100 bp by default, and gap size estimations will be attempted if you use `-D`.

**Comment by lcoombe** [comment]
Closing this for now due to inactivity -- feel free to re-open if you still have questions.
