### ISSUE TITLE
question about 'Barcode whitelist filtering'

### ISSUE THREAD

**Issue by longzhangnation** [bcgsc/arcs#79]
Helllo,
  Recently I read a paper saying that 'Linked reads with barcodes that did not match the company’s barcode whitelist were filtered out.'. So I was wondering conld longranger basic achieve that goal? Or what can we to make this happen?
  Thanks.

**Comment by lcoombe** [comment]
Hi @longzhangnation ,

Sorry for the delayed response!

Yes, in fact `longranger basic` does check the barcodes against their whitelist when it is removing the barcode from the first read. So, if you have run your reads through `longranger basic`, then all of your barcodes have already been checked against the white list.

**Comment by longzhangnation** [comment]
Thanks a lot.
