### ISSUE TITLE
Barcode length for Arcs

### ISSUE THREAD

**Issue by danshu** [bcgsc/arcs#8]
Hi,

I have two chromium libraries and these two libraries have some shared barcodes. To scaffolding using the two libraries, I have to change the barcodes to distinguish between the two libraries. I plan to append A to the end of barcodes in library 1 and append C to the end of barcodes in library 2. So does Arcs require the barcode length to be 16? Or the barcode length does not matter?

Best,
Danshu

**Comment by danshu** [comment]
The length of the index can be set using the "-i" option.  ( 14 for GemCode, 16 for Chromium (default: 16)). Can I set it to 17?

**Comment by warrenlr** [comment]
Hi Danshu, the -i option is deprecated in ARCS v1.0.1. Any sequence string after "_" is considered a barcode, so you may append letters to distinguish between libraries, as stated in your original message. I think v1.0.1 was pushed on to the main branch, I'll double check that.

Rene
