### ISSUE TITLE
arcs-tigmint error 

### ISSUE THREAD

**Issue by mas160** [bcgsc/arcs#85]
As mentioned previously I am using one assembly file and 3 barcoded files with arcs-make. I merged those barcoded files using zcat so tat I can run them through arcs-make but I am getting the following error:
[gzread] <fd:3>: incorrect data check 
[bam_sort_core] merging from 512 files and 8 in-memory blocks... time user=1178869.19s system=5098.15s elapsed=148254.18s cpu=798% memory=11128 job= time user=2190.34s system=599.57s elapsed=148254.18s cpu=1% memory=7 job= time user=40187.56s system=959.96s elapsed=167762.88s cpu=24% memory=6741 job= 
make[1]: *** [vero1.all.sortbx.bam] Error 1 
make[1]: *** Deleting file `vero1.all.sortbx.bam' 
make[1]: Leaving directory `...' 
make: *** [vero1.tigmint.fa] Error 2

**Comment by lcoombe** [comment]
For posterity - Discussion about this error is in #84
