### ISSUE TITLE
no such file or directory: /tigmint-molecule

### ISSUE THREAD

**Issue by mas160** [bcgsc/arcs#87]
i,
I used arcs-make to run arcs with tigmint but I am getting the error : tigmint command not found from this line :
$(gtime) tigmint tigmint draft=$(draft) reads=$(reads) minsize=$(minsize) as=$(as) nm=$(nm) dist=$(dist) mapq=$(mapq) trim=$(trim) span=$(span) window=$(window) t=$t

so I added tigmint-make file to my PATH and changed the command line to:
$(gtime) ./tigmint-make tigmint draft=$(draft) reads=$(reads) minsize=$(minsize) as=$(as) nm=$(nm) dist=$(dist) mapq=$(mapq) trim=$(trim) span=$(span) window=$(window) t=$t

But after this error appears:
/tigmint-molecule -a0.65 -n5 -q0 -d50000 -s2000 vero1.L2.barcoded.sortbx.bam | sort -k1,1 -k2,2n -k3,3n >vero1.L2.barcoded.as0.65.nm5.molecule.size2000.bed
zsh:1: no such file or directory: /tigmint-molecule
make[1]: *** [vero1.L2.barcoded.as0.65.nm5.molecule.size2000.bed] Error 127
make[1]: *** Deleting file `vero1.L2.barcoded.as0.65.nm5.molecule.size2000.bed'
make[1]: Leaving directory '
make: *** [vero1.tigmint.fa] Error 2
Why is tigmint-molecule called?
If /tigmint-make is not the right file to use could you please provide me the actual /tigmint file tat is called in arcs-make?
Thank you

**Comment by lcoombe** [comment]
Hi @mas160,

Can you add the result of `echo $PATH`? `tigmint-molecule` is an executable in the `bin` directory, and is a main step of `tigmint`. `tigmint-make` is a Makefile, so runs a series of commands, including `bwa mem` alignments, `tigmint-molecule` and `tigmint-cut`.

**Comment by mas160** [comment]
i am using compute canada servers  so the softwares are loaded modules therefore they will not appear if I use echo $PATH

**Comment by lcoombe** [comment]
Since it cannot find `tigmint-molecule`, there is something wrong with your paths or loaded modules. `tigmint-molecule` is a python script found in the `bin` directory.

**Comment by mas160** [comment]
It wasn't showing so I reloaded the pipeline and now it is working. Now the issue is when I run arcs-make with and without tigmint I have zero scaffolding and when looking at the log I noticed that zero files were merged during the bwa-mem step to generate the sortbx.bam file.

**Comment by lcoombe** [comment]
The `sortbx.bam` file is a file required by Tigmint actually, not by ARCS. ARCS will use a BAM file sorted by name, not BX tag.
Regardless, this isn't anything to worry about. It means that all of the alignments were kept in memory and didn't have to be written out to temporary files on disk.

As for the issue with no scaffolding taking place, is the graph file from ARCS empty (`*_original.gv`)? Take a look at the file and see if there are any edges in the graph. An empty graph file will result in no scaffolding and is usually a symptom if file formatting issues.

**Comment by lcoombe** [comment]
That graph file isn't empty, actually -- you can see two edges there.

How many pieces are in your original file? What is the approximate N50? What parameters are you using? It is strange that there are only 4 different scaffolds in the scaffold graph.

**Comment by mas160** [comment]
My mistake, all the scaffolds are not appearing...
I have 56471 scaffolds with a L50 of 23 and a N50 of 29636809. it was scaffolded with supernova and I used default parameters in arcs-make.

**Comment by lcoombe** [comment]
That is a very contiguous assembly! It is possible that the scaffolding information in the linked reads has been maxed out by Supernova, and that there are no more joins to be made.

Could you post the log from the ARCS step? I can take a look to see if I see anything that would help.

**Comment by mas160** [comment]
arcs -f vero1.renamed.fa -a vero1_bamfiles.fof -v -c 5 -m 50-10000 -s 98 -r 0.05 -e 30000 -z 500 -d 0 --gap 100 -b vero1_c5_m50-10000_s98_r0.05_e30000_z500 --barcode-counts barcodeMultiplicityArcs.tsv
Reading user inputs...
Finished reading user inputs...entering runArcs()...
Running: arcs 1.1.0
ARCS method
 pid 2260
 -c 5
 -d 0
 -e 30000
 -l 0
 -m 50-10000
 -r 0.05
 -v 1
 -z 500
 --gap=100
 -s 98
 -b vero1_c5_m50-10000_s98_r0.05_e30000_z500
 -g vero1_c5_m50-10000_s98_r0.05_e30000_z500.dist.gv
 --barcode-counts=barcodeMultiplicityArcs.tsv
 --tsv=vero1_c5_m50-10000_s98_r0.05_e30000_z500_main.tsv
 -a vero1_bamfiles.fof
 -f vero1.renamed.fa
 -u NA
 vero1.sorted.bam

=> Getting scaffold sizes... Mon Jan 20 11:29:34 2020
Saw 56471 sequences.

=> Reading alignment files... Mon Jan 20 11:29:48 2020
Reading alignments: vero1.sorted.bam
Cumulative memory usage: 17864

=> Pairing scaffolds... Mon Jan 20 11:29:52 2020

=> Creating the graph... Mon Jan 20 11:29:52 2020

=> Writing graph file... Mon Jan 20 11:29:52 2020

      Max Degree (-d) set to: 0. Will not delete any vertices from graph.
      Writing graph file to vero1_c5_m50-10000_s98_r0.05_e30000_z500_original.gv...

=> Creating the ABySS graph... Mon Jan 20 11:29:52 2020

=> Writing the ABySS graph file... Mon Jan 20 11:29:52 2020

{ "All_barcodes_unfiltered":4132, "All_barcodes_filtered":2392, "Scaffold_end_barcodes":1651, "Min_barcode_reads_threshold":50, "Max_barcode_reads_threshold":10000 }

=> Writing TSV file... Mon Jan 20 11:29:52 2020

=> Writing reads per barcode TSV file... Mon Jan 20 11:29:52 2020

=> Done.
Mon Jan 20 11:29:52 2020
python /lustre03/project/6037355/marie07/./makeTSVfile.py vero1_c5_m50-10000_s98_r0.05_e30000_z500_original.gv vero1_c5_m50-10000_s98_r0.05_e30000_z500.tigpair_checkpoint.tsv vero1.renamed.fa
ln -s vero1_c5_m50-10000_s98_r0.05_e30000_z500.tigpair_checkpoint.tsv vero1_c5_m50-10000_s98_r0.05_e30000_z500_l5_a0.3.tigpair_checkpoint.tsv
LINKS -f vero1.renamed.fa -s empty.fof -b vero1_c5_m50-10000_s98_r0.05_e30000_z500_l5_a0.3 -l 5 -a 0.3 -z 500
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = (unset),
        LC_ALL = (unset),
        LANG = "C.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").

Running: /cvmfs/soft.computecanada.ca/easybuild/software/2017/avx2/Compiler/gcc5.4/links/1.8.6/bin/LINKS [v1.8.6]
-f vero1.renamed.fa
-s empty.fof
-m
-d 4000
-k 15
-e 0.1
-l 5
-a 0.3
-t 2
-o 0
-z 500
-b vero1_c5_m50-10000_s98_r0.05_e30000_z500_l5_a0.3
-r
-p 0.001
-x 0

----------------- Verifying files -----------------

Checking sequence target file vero1.renamed.fa...ok


Scaffolding mid-point files:
vero1_c5_m50-10000_s98_r0.05_e30000_z500_l5_a0.3.tigpair_checkpoint.tsv
vero1_c5_m50-10000_s98_r0.05_e30000_z500_l5_a0.3.simplepair_checkpoint.tsv
detected; LINKS will skip contig pairing and use info from files instead : Mon Jan 20 11:30:04 EST 2020

Reading sequences from vero1.renamed.fa : Mon Jan 20 11:30:04 EST 2020

done.
Reading sequence pairs from vero1_c5_m50-10000_s98_r0.05_e30000_z500_l5_a0.3.tigpair_checkpoint.tsv : Mon Jan 20 11:30:21 EST 2020

done.
Building scaffolds : Mon Jan 20 11:30:21 EST 2020

done.
Building .gv graph : Mon Jan 20 11:30:22 EST 2020


=>Scaffolding ended : Mon Jan 20 11:30:22 EST 2020
Scaffolds layout in: vero1_c5_m50-10000_s98_r0.05_e30000_z500_l5_a0.3.scaffolds
Scaffold graph in: vero1_c5_m50-10000_s98_r0.05_e30000_z500_l5_a0.3.gv


=>Making FASTA file : Mon Jan 20 11:30:22 EST 2020
Scaffolds FASTA in : vero1_c5_m50-10000_s98_r0.05_e30000_z500_l5_a0.3.scaffolds.fa


=>Wrote correspondence file tracking LINKScontigID <=> OriginalContigNames : vero1_c5_m50-10000_s98_r0.05_e30000_z500_l5_a0.3.assembly_correspondence.tsv

Scaffolding executed normally Mon Jan 20 11:30:32 EST 2020
/cvmfs/soft.computecanada.ca/easybuild/software/2017/avx2/Compiler/gcc5.4/links/1.8.6/bin/LINKS [v1.8.6] terminated successfully on Mon Jan 20 11:30:32 EST 2020

**Comment by lcoombe** [comment]
@mas160 - Does the number of barcodes make sense to you? Having only 4132 barcodes seems low to me, but I'm not sure of the expected number based on the expected genome size of the species you are assembling.

**Comment by mas160** [comment]
it seemed low to me too because I have 3 interleaved files that I concatenated into one and the targeted genome size is 2.9gb

**Comment by lcoombe** [comment]
That would be fine for troubleshooting purposes, but I wouldn't suggest running ARCS iteratively like that for your final run. ARCS would give the best results if it has all the information to distinguish strong joins from noise.

You could try counting the number of barcodes in the reads file yourself with a one-liner/simple script to gauge what is going on. I assume the reads are properly formatted in the `BX` tag of the read headers?

**Comment by lcoombe** [comment]
Closing this for now, but feel free to re-open if you're still having issues.
