### ISSUE TITLE
Error ARCS: sequence with ID "X" empty

### ISSUE THREAD

**Issue by mas160** [bcgsc/arcs#93]
Hi,

I was running arcs on my assembly and following bwa alignement, I received this error and the job was terminated:
arcs -f vero1f.renamed.fa -a vero1f_bamfiles.fof -v -c 5 -m 50-20000 -s 98 -r 0.05 -e 90000 -z 500 -d 0 --gap 100 -b vero1f_c5_m50-20000_s98_r0.05_e90000_z500 --barcode-counts barcodeMultiplicityArcs.tsv
Reading user inputs...
Finished reading user inputs...entering runArcs()...
Running: arcs 1.1.0
ARCS method
 pid 134824
 -c 5
 -d 0
 -e 90000
 -l 0
 -m 50-20000
 -r 0.05
 -v 1
 -z 500
 --gap=100
 -s 98
 -b vero1f_c5_m50-20000_s98_r0.05_e90000_z500
 -g vero1f_c5_m50-20000_s98_r0.05_e90000_z500.dist.gv
 --barcode-counts=barcodeMultiplicityArcs.tsv
 --tsv=vero1f_c5_m50-20000_s98_r0.05_e90000_z500_main.tsv
 -a vero1f_bamfiles.fof
 -f vero1f.renamed.fa
 -u NA
 vero1f.sorted.bam

=> Getting scaffold sizes... Fri May 29 11:59:23 2020
vero1f.renamed.fa:94830: error: sequence with ID `47415' is empty
make: *** [vero1f_c5_m50-20000_s98_r0.05_e90000_z500_original.gv] Error 1

This is the first time I am getting this error. What do you think is the cause?

Thank you.

Best,

**Comment by lcoombe** [comment]
Hi @mas160 ,

Have you taken a look at the offending sequence in your `vero1f.renamed.fa` file? Do you see anything unusual with the sequence?

**Comment by mas160** [comment]
Hi,

I did not see anything unusual so I decided to recreate vero1f.renamed.fa and rerun bwa index to see if it solves the issue

**Comment by lcoombe** [comment]
Ok sure, let me know if that doesn't fix the issue. If you are still having problems, it would help to see your full command, log and the sequence that it is complaining about.

**Comment by mas160** [comment]
Hi again,

As I mentioned previously I tried running the job again with tigmint and this time it fails when trying to create the fai file. The error message I get is: [faidx] Could not build fai index vero1f.fa.fai without any addditional information as to why it fails. I tried using just the " samtools faidx" command on my other fasta files but I get the same error for all the output files generated using cobbler/RAILS minimapSTREAM.sh script....
Do you have an idea as to why this is happening after running cobbler/RAILS?

Best,

**Comment by lcoombe** [comment]
Hi @mas160,
Unfortunately I can only guess what's going on -- as a first test I would run the fasta file through `seqtk seq` to get rid of any possible extra newlines or the like, and rename the headers to something simple like ">1", ">2"...
If that doesn't work, perhaps you could post a sample of the fasta file, or you could send me your fasta file?

**Comment by mas160** [comment]
Hi,

I will try it and let you know how it goes. Thank you again for your time and help.

Best,
