### ISSUE TITLE
Sideloading a BAM

### ISSUE THREAD

**Issue by andreaswallberg** [bcgsc/arcs#94]
Dear developers,

I checked among the issues but could not find any information with regards to this question. Is it possible to provide a pre-mapped and correctly sorted BAM file to ARCS?

This basically sidesteps using BWA and sideloads the BAM. The arcs-make script make it seem like I could pretty much comment out the lines corresponding to mapping and pass my own file.

The reason I wonder is that the particular genome and dataset I work on is massive and needs multi-node mapping on a cluster to complete. Running BWA from within ARCS is not feasible for me.

Cheers!

**Comment by lcoombe** [comment]
Hi @andreaswallberg,

Yes, you can certainly provide a BAM file to ARCS without having the `arcs-make` Makefile perform that step for you. You have a couple of options:
1. Run the required commands manually. This would require running `arcs`, the `makeTSVfile.py` and `LINKS` to construct the scaffold graph and output the scaffolds in fasta format. You could take a look at the Makefile to see the details of how these commands should be run. 

2. Create soft-links to your files to name them as expected by the `arcs-make` Makefile to make it trigger at the `arcs` step, after the alignments.
This is what I normally do in this situation (when I want to do parallel BWA alignments), but it does require a bit of knowledge about Makefiles and is a bit fiddly. Basically, you can do a dry-run (supply `-n` to `arcs-make`) and see what commands would be run if the whole pipeline was triggered. Then, you can create softlinks to your assembly file and alignments file-of-file with the naming expected by the Makefile. Then, when you run `arcs-make`, if the Makefile already sees these intermediate files present in your working directory, it will decide that the alignment rule has already been satisfied, and move on to constructing the scaffold graph (`arcs`).

Hope that makes sense -- let me know if you have any questions about any of the above options.
Thank you for your interest in ARCS!
Lauren

**Comment by andreaswallberg** [comment]
Many thanks for the super fast response @lcoombe !

I will try it. If you don't mind, I suggest keeping this ticket open for now and I will provide feedback once I have tried your suggestions.

Cheers!

**Comment by lcoombe** [comment]
Sounds like a plan - Good luck!
