### ISSUE TITLE
Boost 1.58.0 address

### ISSUE THREAD

**Issue by REDitter** [bcgsc/arcs#96]
Just a heads up, after directly cloning arcs (git clone https://github.com/bcgsc/arcs.git)
and following the instructions when I run ./configure  && make
the address for boost "http://downloads.sourceforge.net/project/boost/boost/1.58.0/1_58_0.tar.bz2"
is incorrect, or at least when I run wget it produces a connection failure.

I believe the address should be "http://downloads.sourceforge.net/project/boost/boost/1.58.0/boost_1_58_0.tar.bz2"
and "tar jxf boost_1_58_0.tar.bz2"

**Comment by lcoombe** [comment]
Hi @REDitter,

Thanks for the report! This is fixed in 83805a8.
