### ISSUE TITLE
ARCS finds 0 barcodes when using TELLSeq reads instead of Chromium reads 

### ISSUE THREAD

**Issue by grendon** [bcgsc/arcs#99]
I have TELLSeq reads that I have reformatted as 10x reads ; yet, arcs does not find barcodes.
I know that the barcode lengths are different; but other than that, they should work. Right?

This is how my interleaved file of reads looks like

<pre>
@A00835:176:HTCNTDRXX:2:2101:1136:1016_GTCAGTGCGGTTAGGATA
TNGTGGATTTAACAAATTTAATTATGCAATATTTCAGTCGGCGACCGCACATTTTTATAAAATAAAGAGATTGCAATTGAGAAGATGGCAAAGGGGAAAGGGAAGAAGTAAATGTGTCGAAAGAATGGGCGGAATTTAAATAAAATGTAA
+
F#FFFFF:FF:FFF:,FFF:FFFFFFFFF:FF:FFFFFF:F::FFFFFFFFFFF,FFFFFF:,:FF::F:,FF,FFFFFF,:FFFF:F:::,,F:FF,,:,FF,,:::F,,,:,F,,,F,,FF,::F,:,,,,,,,F:,,F,,:,F,::,
@A00835:176:HTCNTDRXX:2:2101:1136:1016_GTCAGTGCGGTTAGGATA
GCCGTGTTGATGTGGAAAAACGATAGGAGCGATTAAGATTTGAGAATTATTACTCTATATTATTTTTTATTTAAATTCGTTGGATTATTTCGTGTTTTTTTTTTGATAACTTTGAAATTTGGAATAGTATAAAATGAACTCTATTATTTG
+
,,,:F,:F,:F,FF:F::::,F,FF:,F,,:F,,,,,FFFF,F::F,F,F,:,:,,:,,FF:,,FF:,,:,F:,,F,,,:,,,,FF,,F,,:F,,,,F,F,,FF,,:,,,:,,,,,,F,,,,,,::,F,F,F:,:F,,,F,F,,,::,,,
@A00835:176:HTCNTDRXX:2:2101:1208:1016_GGAATCAACGATACGATG
TNCGCTTTTTCAAATCTCAGAATTCAAGTTCTCGTTTACTTTTTGTCGTACGTTAATTCATAAAAGTTTGATATCAAAAGTAGAAATGCTTGTAAGATTTATTATTATTATTGAGTTGTGTTGGAATGATAATAATTAAGTAGAGTTGGT
+
F#FFFFFFFFFFFFF:FFF:FFFFFFFFFF,F:,FFFF,F,FFFF:,,,:,FF:FFFF:,FFF::F::FFFF:F,:,,F,:,,:F:F,,,FF:,:,,,,F:,,,,:,FF,,,,,:,F,,,,F,,,,,:,,,,,,,,,,,,,,F,,,,,,:
@A00835:176:HTCNTDRXX:2:2101:1208:1016_GGAATCAACGATACGATG
CCAAATGGACTTATTTTTTATCTTTTAAACAGAAGTGTAAAATATTAATAAATCTTAATAGGATTTCTGGTTTTTTTTTGTTTGTTTTTTGATTTAGATTAGGTCAATATTTATAAGATAAATTTTGTTGTTAGATTTTTAATATAGTAT
+
,,,F,F,:,,,,,:F,,::,F,:,,F,,,,,,:,,FFF,,:,F,:FF,F,,,F,:F:,,F,,,::F,:,,,,,:,F,,F,,,,,:FFF,F,,FFFF,:,FF,,,,F,,:,,,,,,:,,,:,,FF,,,F,,::,F,,:,,,,:F::,,:F:

</pre>

FYI: I also produced interleaved reads that embed/prepend  the barcode in each read of R1. arcs doesn't find barcodes in that file either.

The odd thing is that supernova likes my files and produces acceptable assemblies; a little bit more fragmented than those with PacBio HiFi reads for the same species. Which is to be expected.  But the point is that the formatting script seems to be working fine.

The N50 of my assembly is 97672. The number of scaffolds  is 4326

My version is ARCS/1.1.1.   This is my arcs cmd:

<pre>
arcs -v -k 21 --arks -f HiCanu.fasta   Sample_S2_L002_10x_interleaved.fq
</pre>

This is a snippet of the log file:

<pre>
clipped

Processed 460000000 read pairs.
Processed 470000000 read pairs.
Stored read pairs: 0
Skipped invalid read pairs: 0
Skipped unpaired reads: 0
Skipped reads pairs without a good contig: 0
Total valid kmers: 0
Number invalid kmers: 0
Number of kmers found in ContigKmap: 0
Number of kmers recorded in Ktrack: 0
Number of kmers found in ContigKmap but duplicate: 0
Number of reads passing jaccard threshold: 0
Number of reads failing jaccard threshold: 0
WARNING:: Your chromium read file has 239176786 readpairs that have an empty barcode.Cumulative memory usage: 3318060

=> Pairing scaffolds... Fri Nov 13 16:10:15 2020

=> Creating the graph... Fri Nov 13 16:10:15 2020

=> Writing graph file... Fri Nov 13 16:10:15 2020

      Max Degree (-d) set to: 0. Will not delete any vertices from graph.
      Writing graph file to HiCanu.fasta.scaff_arks_c5_k21_j0.55_l0_d0_e30000_r0.05_original.gv...

=> Creating the ABySS graph... Fri Nov 13 16:10:15 2020

=> Writing the ABySS graph file... Fri Nov 13 16:10:15 2020

{ "All_barcodes_unfiltered":0, "All_barcodes_filtered":0, "Scaffold_end_barcodes":0, "Min_barcode_reads_threshold":50, "Max_barcode_reads_threshold":10000 }

=> Writing TSV file... Fri Nov 13 16:10:15 2020

=> Done.
</pre>

Your help would be greatly appreciated!

**Comment by lcoombe** [comment]
Hi @grendon,

That's really cool that you're trying ARCS/ARKS with TELLseq reads - we have just started playing around with the data type in our group.

Could you try formatting your reads with the barcode in the BX tag of the header? Like the format that is output by longranger basic. Ex:
```
@A00835:176:HTCNTDRXX:2:2101:1136:1016 BX:Z:GTCAGTGCGGTTAGGATA
```

Let me know if that fixes the issue - Thanks for your interest in ARCS!
Lauren

**Comment by grendon** [comment]
It worked!!  Thank you so very much!!

FYI:  These are the last lines of my log file

<pre>
{ "All_barcodes_unfiltered":15385369, "All_barcodes_filtered":1539622, "Scaffold_end_barcodes":3734137, "Min_barcode_reads_threshold":50, "Max_barcode_reads_threshold":10000 }

=> Writing TSV file... Wed Nov 18 05:25:05 2020

=> Done.
Wed Nov 18 05:25:09 2020
</pre>

**Comment by lcoombe** [comment]
Excellent! I'm glad that fixed it - I'll update the README to make that more clear to do the formatting for `--arks` in that way.
Those lines of the log look good to me!
